/**
 * Dashboard Store
 *
 * Bridge between HardwareView and TopBar (UI consumer).
 * statusCounts are computed from espStore via getESPStatus (reactive).
 * TopBar reads counts/breadcrumb and writes filter changes.
 *
 * Extended with Custom Dashboard Layout management (Phase 2).
 * Phase 3: Server-API sync (POST/PUT/DELETE) with localStorage as cache.
 */

import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { useEspStore } from '@/stores/esp'
import { getESPStatus } from '@/composables/useESPStatus'
import { dashboardsApi, type DashboardDTO } from '@/api/dashboards'

import { findFirstFreePosition } from '@/utils/gridLayout'
import { createLogger } from '@/utils/logger'

const logger = createLogger('DashboardStore')

export type StatusFilter = 'online' | 'offline' | 'warning' | 'safemode'
export type TypeFilter = 'all' | 'mock' | 'real'

/** Widget type identifiers */
export type WidgetType = 'sensor-tile' | 'line-chart' | 'gauge' | 'sensor-card' |
  'historical' | 'actuator-card' | 'actuator-runtime' |
  'esp-health' | 'alarm-list' | 'multi-sensor' | 'statistics' |
  'fertigation-pair' | 'comparison-boxplot' | 'correlation-scatter' |
  'climate-rule-health' | 'claude-chat'

/** Single widget configuration */
export interface DashboardWidget {
  id: string
  type: WidgetType
  x: number
  y: number
  w: number
  h: number
  config: {
    sensorId?: string
    actuatorId?: string
    espId?: string
    gpio?: number
    sensorType?: string
    zoneId?: string
    timeRange?: '1h' | '6h' | '24h' | '7d' | '30d' | 'custom'
    showThresholds?: boolean
    title?: string
    color?: string
    /** Comma-separated sensor IDs for multi-sensor widget */
    dataSources?: string
    /** Explicit Y-axis min override */
    yMin?: number
    /** Explicit Y-axis max override */
    yMax?: number
    /** Zone filter for alarm-list, esp-health, actuator-runtime (zone_id or null = all zones) */
    zoneFilter?: string | null
    /** Show standard deviation in statistics widget (default: true) */
    showStdDev?: boolean
    /** Show quality distribution in statistics widget (default: false) */
    showQuality?: boolean
    /** Warning low threshold (maps to alert_config.custom_thresholds.warning_min) */
    warnLow?: number
    /** Warning high threshold (maps to alert_config.custom_thresholds.warning_max) */
    warnHigh?: number
    /** Alarm/critical low threshold (maps to alert_config.custom_thresholds.critical_min) */
    alarmLow?: number
    /** Alarm/critical high threshold (maps to alert_config.custom_thresholds.critical_max) */
    alarmHigh?: number
    /** AUT-247: SensorTile display mode (numeric|gauge|sparkline|historic) */
    displayMode?: 'numeric' | 'gauge' | 'sparkline' | 'historic'
    /** AUT-247: Live buffer size for sparkline mode */
    liveBufferSize?: number
    /** AUT-1525: Fertigation pair — store config_id, not gpio-key */
    inflowSensorId?: string
    runoffSensorId?: string
  }
}

/** Dashboard scope */
export type DashboardScope = 'zone' | 'zone-tile' | 'cross-zone' | 'sensor-detail'

/** Display target configuration — where and how a dashboard is rendered */
export interface DashboardTarget {
  view: 'monitor' | 'hardware' | 'dashboards'
  placement: 'inline' | 'side-panel' | 'bottom-panel' | 'standalone'
  order?: number
}

export interface DashboardSyncFlags {
  local_only: boolean
  server_synced: boolean
  stale_server_id: string | null
  status: 'local_only' | 'dirty' | 'server_synced' | 'conflict'
  dirty: boolean
  conflict: boolean
  last_sync_attempt_at: string | null
  last_sync_result_at: string | null
  last_sync_message: string | null
}

/** Dashboard layout */
export interface DashboardLayout {
  id: string
  /** Server UUID — set after first successful API sync */
  serverId?: string
  name: string
  description?: string
  createdAt: string
  updatedAt: string
  widgets: DashboardWidget[]
  scope?: DashboardScope
  zoneId?: string
  autoGenerated?: boolean
  sensorId?: string
  target?: DashboardTarget
  syncFlags?: DashboardSyncFlags
}

type LayoutSyncState = DashboardSyncFlags['status']

export const useDashboardStore = defineStore('dashboard', () => {
  const espStore = useEspStore()

  /* ── Visibility ── */
  const showControls = ref(false)

  /* ── Counts (computed from espStore via getESPStatus — reactive to device changes) ── */
  const statusCounts = computed(() => {
    let online = 0, offline = 0, warning = 0, safeMode = 0
    for (const device of espStore.devices) {
      const status = getESPStatus(device)
      switch (status) {
        case 'online':
        case 'stale':
          online++
          break
        case 'offline':
        case 'unknown':
          offline++
          break
        case 'error':
          warning++
          break
        case 'safemode':
          safeMode++
          break
      }
    }
    return { online, offline, warning, safeMode }
  })

  /* ── Device counts (computed from espStore — reactive to device changes) ── */
  const deviceCounts = computed(() => ({
    all: espStore.devices.length,
    mock: espStore.mockDevices.length,
    real: espStore.realDevices.length,
  }))
  const pendingCount = computed(() => espStore.pendingCount)

  /* ── Filters (bidirectional: TopBar writes, DashboardView reads) ── */
  const activeStatusFilters = ref<Set<StatusFilter>>(new Set())
  const filterType = ref<TypeFilter>('all')

  /* ── Breadcrumb (written by Views, read by TopBar) ── */
  const breadcrumb = ref<{
    level: 1 | 2 | 3
    zoneName: string
    deviceName: string
    sensorName: string
    ruleName: string
    dashboardName: string
  }>({
    level: 1,
    zoneName: '',
    deviceName: '',
    sensorName: '',
    ruleName: '',
    dashboardName: '',
  })

  /* ── Modal/Panel triggers (TopBar writes, DashboardView reads) ── */
  const showCreateMock = ref(false)
  const showPendingPanel = ref(false)

  /* ── Navigation request (TopBar → DashboardView) ── */
  const navRequestCount = ref(0)
  const navTarget = ref<1 | 2 | 3>(1)

  /* ── Computed ── */
  const hasProblems = computed(() =>
    statusCounts.value.warning > 0 || statusCounts.value.safeMode > 0
  )

  const problemMessage = computed(() => {
    const { warning, safeMode, offline, online } = statusCounts.value
    if (warning > 0) return `${warning} Gerät(e) mit Fehlern`
    if (safeMode > 0) return `${safeMode} Gerät(e) im Safe-Mode`
    if (offline > 0 && online > 0) return `${offline} Gerät(e) offline`
    return ''
  })

  const hasPendingDevices = computed(() => pendingCount.value > 0)

  /* ── Actions ── */
  function toggleStatusFilter(filter: StatusFilter) {
    const next = new Set(activeStatusFilters.value)
    if (next.has(filter)) next.delete(filter)
    else next.add(filter)
    activeStatusFilters.value = next
  }

  function resetFilters() {
    filterType.value = 'all'
    activeStatusFilters.value = new Set()
  }

  function activate() {
    showControls.value = true
  }

  function deactivate() {
    showControls.value = false
    resetFilters()
  }

  function requestNavigate(level: 1 | 2 | 3) {
    navTarget.value = level
    navRequestCount.value++
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // CUSTOM DASHBOARD LAYOUTS (Phase 2)
  // ═══════════════════════════════════════════════════════════════════════════

  const STORAGE_KEY = 'automation-one-dashboard-layouts'

  /** All saved layouts */
  const layouts = ref<DashboardLayout[]>([])
  /** Currently active layout ID */
  const activeLayoutId = ref<string | null>(null)
  /** Server sync in progress */
  const isSyncing = ref(false)
  /** Debounce timer queued or sync in flight — drives the "Speichern..." chip (AUT-843) */
  const syncPending = ref(false)
  /** Initial server fetch completed at least once (success or failure) */
  const hasFetchedLayouts = ref(false)
  /** Last server sync error message (null = no error) */
  const lastSyncError = ref<string | null>(null)

  /** Currently active layout */
  const activeLayout = computed<DashboardLayout | null>(() =>
    layouts.value.find(l => l.id === activeLayoutId.value) ?? null
  )

  /** Lookup layout by local ID or server UUID (for deep-link robustness) */
  function getLayoutById(id: string): DashboardLayout | undefined {
    return layouts.value.find(l => l.id === id || l.serverId === id)
  }

  function normalizeTimestamp(value?: string | null): string {
    if (!value) return new Date().toISOString()
    const ts = Date.parse(value)
    return Number.isNaN(ts) ? new Date().toISOString() : new Date(ts).toISOString()
  }

  function toEpochMs(value?: string | null): number {
    if (!value) return 0
    const ts = Date.parse(value)
    return Number.isNaN(ts) ? 0 : ts
  }

  function isDirtyStatus(status?: LayoutSyncState): boolean {
    return status === 'dirty' || status === 'conflict'
  }

  function buildSyncFlags(
    serverId?: string,
    staleServerId: string | null = null,
    overrides: Partial<DashboardSyncFlags> = {},
  ): DashboardSyncFlags {
    const defaultStatus: LayoutSyncState = serverId ? 'server_synced' : 'local_only'
    const status = overrides.status ?? defaultStatus
    return {
      local_only: overrides.local_only ?? !serverId,
      server_synced: overrides.server_synced ?? status === 'server_synced',
      stale_server_id: overrides.stale_server_id ?? staleServerId,
      status,
      dirty: overrides.dirty ?? isDirtyStatus(status),
      conflict: overrides.conflict ?? status === 'conflict',
      last_sync_attempt_at: overrides.last_sync_attempt_at ?? null,
      last_sync_result_at: overrides.last_sync_result_at ?? null,
      last_sync_message: overrides.last_sync_message ?? null,
    }
  }

  function withSyncFlags(layout: DashboardLayout, overrides: Partial<DashboardSyncFlags>): DashboardSyncFlags {
    const current = layout.syncFlags ?? buildSyncFlags(layout.serverId)
    return buildSyncFlags(layout.serverId, current.stale_server_id, {
      ...current,
      ...overrides,
    })
  }

  function markLayoutDirty(
    layout: DashboardLayout,
    reasonMessage?: string,
  ): DashboardSyncFlags {
    const localOnly = !layout.serverId
    const status: LayoutSyncState = localOnly ? 'local_only' : 'dirty'
    return withSyncFlags(layout, {
      local_only: localOnly,
      server_synced: false,
      status,
      dirty: true,
      conflict: false,
      last_sync_message: reasonMessage ?? layout.syncFlags?.last_sync_message ?? null,
    })
  }

  function buildLayoutIdentityKey(layout: Pick<DashboardLayout, 'name' | 'scope' | 'zoneId' | 'sensorId' | 'target'>): string {
    const normalizedName = layout.name.toLowerCase().trim()
    const scope = layout.scope ?? 'cross-zone'
    const zoneId = layout.zoneId ?? ''
    const sensorId = layout.sensorId ?? ''
    const targetView = layout.target?.view ?? ''
    const targetPlacement = layout.target?.placement ?? ''
    return [normalizedName, scope, zoneId, sensorId, targetView, targetPlacement].join('|')
  }

  function zoneTileComparator(a: DashboardLayout, b: DashboardLayout): number {
    const aDirtyOrLocal = a.syncFlags?.status === 'local_only' || a.syncFlags?.dirty === true
    const bDirtyOrLocal = b.syncFlags?.status === 'local_only' || b.syncFlags?.dirty === true
    if (aDirtyOrLocal !== bDirtyOrLocal) return aDirtyOrLocal ? -1 : 1

    const aUserOwned = a.autoGenerated === false
    const bUserOwned = b.autoGenerated === false
    if (aUserOwned !== bUserOwned) return aUserOwned ? -1 : 1

    const aUpdated = toEpochMs(a.updatedAt)
    const bUpdated = toEpochMs(b.updatedAt)
    if (aUpdated !== bUpdated) return bUpdated - aUpdated

    return a.id.localeCompare(b.id)
  }

  /**
   * Canonical zone-tile layout per zone (deterministic priority):
   * dirty/local_only > autoGenerated=false > newest updatedAt > lowest id.
   */
  function getCanonicalZoneTileLayout(zoneId: string): DashboardLayout | null {
    const candidates = layouts.value
      .filter((layout) => layout.scope === 'zone-tile' && layout.zoneId === zoneId)
      .sort(zoneTileComparator)
    return candidates[0] ?? null
  }

  function applyLayoutPatch(
    layoutId: string,
    patch: Partial<DashboardLayout>,
    options: { sync?: boolean; reasonMessage?: string } = {},
  ): boolean {
    const idx = layouts.value.findIndex((l) => l.id === layoutId)
    if (idx === -1) return false

    const current = layouts.value[idx]
    const updated: DashboardLayout = {
      ...current,
      ...patch,
      updatedAt: new Date().toISOString(),
    }
    updated.syncFlags = markLayoutDirty(updated, options.reasonMessage)
    layouts.value[idx] = updated
    persistLayouts()
    if (options.sync !== false) {
      syncLayoutToServer(layoutId)
    }
    return true
  }

  /** Load layouts from localStorage */
  function loadLayouts() {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored) {
        const parsed = JSON.parse(stored) as DashboardLayout[]
        layouts.value = parsed.map((layout) => ({
          ...layout,
          createdAt: normalizeTimestamp(layout.createdAt),
          updatedAt: normalizeTimestamp(layout.updatedAt),
          syncFlags: buildSyncFlags(
            layout.serverId,
            layout.syncFlags?.stale_server_id ?? null,
            layout.syncFlags ?? {},
          ),
        }))
        if (layouts.value.length > 0 && !activeLayoutId.value) {
          activeLayoutId.value = layouts.value[0].id
        }
      }
    } catch {
      layouts.value = []
    }
  }

  /** Persist layouts to localStorage */
  function persistLayouts() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(layouts.value))
    } catch {
      // localStorage full or unavailable
    }
  }

  /** Create a new dashboard layout */
  function createLayout(name: string, description?: string, target?: DashboardTarget): DashboardLayout {
    const layout: DashboardLayout = {
      id: `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name,
      description,
      target,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets: [],
      syncFlags: buildSyncFlags(undefined, null, {
        status: 'local_only',
        dirty: true,
        server_synced: false,
        last_sync_message: 'Lokales Dashboard erstellt',
      }),
    }
    layouts.value.push(layout)
    activeLayoutId.value = layout.id
    persistLayouts()
    syncLayoutToServer(layout.id)
    return layout
  }

  /** Save current layout widgets */
  function saveLayout(layoutId: string, widgets: DashboardWidget[]) {
    applyLayoutPatch(layoutId, { widgets }, { reasonMessage: 'Widget-Layout lokal aktualisiert' })
  }

  /** Delete a layout */
  function deleteLayout(layoutId: string) {
    const layout = layouts.value.find(l => l.id === layoutId)
    const serverId = layout?.serverId
    const shouldDeleteRemotely = layout ? shouldDeleteOnServer(layout) : false
    layouts.value = layouts.value.filter(l => l.id !== layoutId)
    if (activeLayoutId.value === layoutId) {
      activeLayoutId.value = layouts.value[0]?.id ?? null
    }
    persistLayouts()
    if (serverId && shouldDeleteRemotely) deleteLayoutFromServer(serverId)
  }

  /** Export layout as JSON string (ensures description is always present) */
  function exportLayout(layoutId: string): string | null {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return null
    return JSON.stringify({ ...layout, description: layout.description || '' }, null, 2)
  }

  /** Import layout from JSON string */
  function importLayout(json: string): DashboardLayout | null {
    try {
      const layout = JSON.parse(json) as DashboardLayout
      layout.id = `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      layout.serverId = undefined
      layout.createdAt = new Date().toISOString()
      layout.updatedAt = new Date().toISOString()
      layout.syncFlags = buildSyncFlags(undefined, null, {
        status: 'local_only',
        dirty: true,
        server_synced: false,
        last_sync_message: 'Dashboard importiert (lokal)',
      })
      layouts.value.push(layout)
      persistLayouts()
      syncLayoutToServer(layout.id)
      return layout
    } catch {
      return null
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // SERVER API SYNC (Phase 3)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Convert server DTO to local DashboardLayout */
  function serverToLocal(dto: DashboardDTO): DashboardLayout {
    return {
      id: dto.id,
      serverId: dto.id,
      name: dto.name,
      description: dto.description || undefined,
      createdAt: normalizeTimestamp(dto.created_at),
      updatedAt: normalizeTimestamp(dto.updated_at),
      widgets: (dto.widgets || []).map(w => ({
        id: w.id,
        type: w.type as WidgetType,
        x: w.x,
        y: w.y,
        w: w.w,
        h: w.h,
        config: (w.config || {}) as DashboardWidget['config'],
      })),
      scope: dto.scope as DashboardScope | undefined,
      zoneId: dto.zone_id || undefined,
      autoGenerated: dto.auto_generated || undefined,
      sensorId: dto.sensor_id || undefined,
      target: (dto.target as unknown) as DashboardTarget | undefined,
      syncFlags: buildSyncFlags(dto.id, null, {
        status: 'server_synced',
        dirty: false,
        conflict: false,
      }),
    }
  }

  /**
   * Fetch dashboards from server API and merge with localStorage cache.
   * Server dashboards take priority (matched by serverId).
   * Called on store init and editor mount.
   */
  async function fetchLayouts(): Promise<void> {
    isSyncing.value = true
    lastSyncError.value = null
    try {
      // API maximum (see GET /dashboards — page_size le 100)
      const pageSize = 100
      const serverDtos: DashboardDTO[] = []
      let page = 1
      let fetchedFromServer = false
      while (true) {
        const response = await dashboardsApi.list(page, pageSize)
        if (!response.success) break
        fetchedFromServer = true
        serverDtos.push(...(response.data || []))
        const totalPages = response.pagination?.total_pages
        if (totalPages != null) {
          if (page >= totalPages) break
          page += 1
          continue
        }
        if ((response.data || []).length < pageSize) break
        page += 1
      }

      if (fetchedFromServer) {
        const serverLayouts = serverDtos.map(serverToLocal)
        const localSnapshot = layouts.value.map((layout) => ({
          ...layout,
          syncFlags: buildSyncFlags(layout.serverId, layout.syncFlags?.stale_server_id ?? null, layout.syncFlags ?? {}),
        }))

        const localByServerId = new Map<string, DashboardLayout>()
        for (const local of localSnapshot) {
          if (local.serverId) localByServerId.set(local.serverId, local)
        }

        const mergedLayouts: DashboardLayout[] = []
        const pendingResync = new Set<string>()
        let conflictCount = 0

        for (const serverLayout of serverLayouts) {
          const serverId = serverLayout.serverId
          if (!serverId) {
            mergedLayouts.push(serverLayout)
            continue
          }

          const local = localByServerId.get(serverId)
          if (!local) {
            mergedLayouts.push(serverLayout)
            continue
          }

          const localUpdatedMs = toEpochMs(local.updatedAt)
          const serverUpdatedMs = toEpochMs(serverLayout.updatedAt)
          const localDirty = Boolean(local.syncFlags?.dirty)

          if (!localDirty && serverUpdatedMs >= localUpdatedMs) {
            mergedLayouts.push(serverLayout)
            continue
          }

          if (localDirty && localUpdatedMs >= serverUpdatedMs) {
            const keptLocal = {
              ...local,
              syncFlags: withSyncFlags(local, {
                status: local.serverId ? 'dirty' : 'local_only',
                dirty: true,
                conflict: false,
                local_only: !local.serverId,
                server_synced: false,
              }),
            }
            mergedLayouts.push(keptLocal)
            pendingResync.add(keptLocal.id)
            continue
          }

          const conflictedLocal: DashboardLayout = {
            ...local,
            syncFlags: withSyncFlags(local, {
              status: 'conflict',
              dirty: true,
              conflict: true,
              local_only: !local.serverId,
              server_synced: false,
              last_sync_message: `Konflikt erkannt (serverId=${serverId})`,
            }),
          }
          conflictCount++
          mergedLayouts.push(conflictedLocal)
        }

        const serverIdSet = new Set(serverLayouts.map((layout) => layout.serverId).filter(Boolean))
        const localOnly = localSnapshot.filter((layout) => !layout.serverId || !serverIdSet.has(layout.serverId))
        const normalizedLocalOnly = localOnly.map((layout) => {
          if (layout.serverId && !serverIdSet.has(layout.serverId)) {
            const staleServerId = layout.serverId
            const clearedServerIdLayout: DashboardLayout = {
              ...layout,
              serverId: undefined,
            }
            return {
              ...clearedServerIdLayout,
              syncFlags: buildSyncFlags(undefined, staleServerId, {
                ...layout.syncFlags,
                status: 'local_only',
                local_only: true,
                server_synced: false,
                dirty: true,
                conflict: false,
                stale_server_id: staleServerId,
                last_sync_message: `Server-Dashboard fehlt (serverId=${staleServerId}), Neu-Sync erforderlich`,
              }),
            }
          }

          return {
            ...layout,
            syncFlags: buildSyncFlags(
              layout.serverId,
              layout.syncFlags?.stale_server_id ?? null,
              layout.syncFlags ?? {},
            ),
          }
        })

        layouts.value = [...mergedLayouts, ...normalizedLocalOnly]

        // Enforce target-slot uniqueness after loading from server.
        // Legacy data may contain multiple layouts sharing the same view+placement
        // (created before uniqueness was enforced by setLayoutTarget). Keep only
        // the most-recently-updated entry per slot; clear the rest and sync to server.
        {
          const slotMap = new Map<string, DashboardLayout[]>()
          for (const layout of layouts.value) {
            if (!layout.target?.view || !layout.target?.placement) continue
            const key = `${layout.target.view}:${layout.target.placement}`
            const group = slotMap.get(key)
            if (group) {
              group.push(layout)
            } else {
              slotMap.set(key, [layout])
            }
          }
          for (const group of slotMap.values()) {
            if (group.length <= 1) continue
            const sorted = [...group].sort(
              (a, b) =>
                new Date(b.updatedAt ?? 0).getTime() - new Date(a.updatedAt ?? 0).getTime(),
            )
            for (let i = 1; i < sorted.length; i++) {
              const dup = sorted[i]
              applyLayoutPatch(
                dup.id,
                { target: undefined },
                { reasonMessage: 'Duplicate monitor slot cleared (uniqueness enforcement)' },
              )
              logger.info(`Cleared duplicate monitor slot target from layout "${dup.name}" (${dup.id})`)
            }
          }
        }

        persistLayouts()

        logger.info(
          `Fetched ${serverLayouts.length} dashboards from server, ${localOnly.length} local-only, ${conflictCount} conflicts`,
        )

        // Proactive orphan sync: push local-only dashboards to server.
        // Also catches layouts with stale serverIds (cleared by PUT 404 recovery).
        const orphans = layouts.value.filter((l) => !l.serverId)
        if (orphans.length > 0) {
          logger.info(`Syncing ${orphans.length} orphan dashboard(s) to server`)
          for (const orphan of orphans) {
            syncLayoutToServer(orphan.id)
          }
        }

        if (pendingResync.size > 0) {
          for (const layoutId of pendingResync) {
            syncLayoutToServer(layoutId)
          }
        }
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e)
      lastSyncError.value = msg
      logger.warn('Failed to fetch dashboards from server, using localStorage cache:', msg)
    } finally {
      isSyncing.value = false
      hasFetchedLayouts.value = true
    }
  }

  /** Per-layout debounce timers (prevents losing edits when switching dashboards) */
  const _saveDebounceTimers = new Map<string, ReturnType<typeof setTimeout>>()
  const _syncInFlight = new Set<string>()
  const _deleteInFlightServerIds = new Set<string>()
  const SAVE_DEBOUNCE_MS = 2000

  /** Build server payload from a local layout */
  function buildSyncPayload(layout: DashboardLayout) {
    return {
      name: layout.name,
      description: layout.description || '',
      widgets: layout.widgets.map(w => ({
        id: w.id,
        type: w.type,
        x: w.x,
        y: w.y,
        w: w.w,
        h: w.h,
        config: w.config || {},
      })),
      scope: layout.scope,
      zone_id: layout.zoneId,
      auto_generated: layout.autoGenerated || false,
      sensor_id: layout.sensorId,
      target: (layout.target as Record<string, unknown> | undefined) || null,
    }
  }

  /** Check if an axios error has a specific HTTP status code */
  function isHttpStatus(error: unknown, status: number): boolean {
    if (error && typeof error === 'object' && 'response' in error) {
      const resp = (error as { response?: { status?: number } }).response
      return resp?.status === status
    }
    return false
  }

  function setSyncFlagsForLayout(
    layoutId: string,
    updater: (layout: DashboardLayout) => DashboardSyncFlags,
  ): void {
    const idx = layouts.value.findIndex((layout) => layout.id === layoutId)
    if (idx === -1) return
    const current = layouts.value[idx]
    layouts.value[idx] = {
      ...current,
      syncFlags: updater(current),
    }
    persistLayouts()
  }

  function shouldDeleteOnServer(layout: DashboardLayout): boolean {
    if (!layout.serverId) return false
    if (layout.syncFlags?.status === 'local_only') return false
    if (layout.syncFlags?.stale_server_id === layout.serverId) return false
    return true
  }

  async function performSyncLayout(
    layoutId: string,
    reason: 'debounce' | 'flush' | 'retry' | 'beforeunload' = 'debounce',
  ): Promise<boolean> {
    if (_syncInFlight.has(layoutId)) return false
    const layout = layouts.value.find((item) => item.id === layoutId)
    if (!layout) return false

    _syncInFlight.add(layoutId)
    const attemptAt = new Date().toISOString()
    setSyncFlagsForLayout(layoutId, (current) => withSyncFlags(current, {
      last_sync_attempt_at: attemptAt,
      last_sync_message: `Sync gestartet (${reason})`,
    }))

    try {
      const latest = layouts.value.find((item) => item.id === layoutId)
      if (!latest) return false

      const payload = buildSyncPayload(latest)
      let nextServerId = latest.serverId
      let staleServerId = latest.syncFlags?.stale_server_id ?? null

      if (latest.serverId) {
        try {
          await dashboardsApi.update(latest.serverId, payload)
        } catch (putError) {
          if (!isHttpStatus(putError, 404)) throw putError
          staleServerId = latest.serverId
          setSyncFlagsForLayout(layoutId, (current) => withSyncFlags(current, {
            stale_server_id: staleServerId,
            status: 'local_only',
            local_only: true,
            server_synced: false,
            dirty: true,
            conflict: false,
            last_sync_message: `Server-Dashboard fehlte (404), Neu-Erstellung läuft`,
          }))
          nextServerId = undefined
        }
      }

      if (!nextServerId) {
        const response = await dashboardsApi.create(payload)
        if (!response.success || !response.data?.id) {
          throw new Error('Server hat keine Dashboard-ID geliefert')
        }
        nextServerId = response.data.id
      }

      const successAt = new Date().toISOString()
      const idx = layouts.value.findIndex((item) => item.id === layoutId)
      if (idx !== -1) {
        const merged: DashboardLayout = {
          ...layouts.value[idx],
          serverId: nextServerId,
        }
        merged.syncFlags = buildSyncFlags(nextServerId, staleServerId, {
          status: 'server_synced',
          local_only: false,
          server_synced: true,
          dirty: false,
          conflict: false,
          last_sync_attempt_at: attemptAt,
          last_sync_result_at: successAt,
          last_sync_message: `Sync erfolgreich (${reason})`,
        })
        layouts.value[idx] = merged
        persistLayouts()
      }
      lastSyncError.value = null
      return true
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Layout konnte nicht gespeichert werden'
      const failedAt = new Date().toISOString()
      lastSyncError.value = msg
      setSyncFlagsForLayout(layoutId, (current) => {
        const localOnly = !current.serverId
        const hadConflict = current.syncFlags?.status === 'conflict'
        const status: LayoutSyncState = hadConflict ? 'conflict' : (localOnly ? 'local_only' : 'dirty')
        return withSyncFlags(current, {
          status,
          local_only: localOnly,
          server_synced: false,
          dirty: true,
          conflict: hadConflict,
          last_sync_attempt_at: attemptAt,
          last_sync_result_at: failedAt,
          last_sync_message: msg,
        })
      })
      logger.warn(`Failed to sync layout "${layout.name}" to server`, e)
      return false
    } finally {
      _syncInFlight.delete(layoutId)
      if (_saveDebounceTimers.size === 0 && _syncInFlight.size === 0) syncPending.value = false
    }
  }

  /** Sync layout to server (fire-and-forget, debounced per layout) */
  function syncLayoutToServer(layoutId: string): void {
    const existing = _saveDebounceTimers.get(layoutId)
    if (existing) clearTimeout(existing)

    syncPending.value = true
    const timer = setTimeout(() => {
      _saveDebounceTimers.delete(layoutId)
      void performSyncLayout(layoutId, 'debounce')
    }, SAVE_DEBOUNCE_MS)
    _saveDebounceTimers.set(layoutId, timer)
  }

  async function flushPendingSyncs(
    reason: 'flush' | 'beforeunload' | 'retry' = 'flush',
  ): Promise<{ flushed: number; succeeded: number; failed: number }> {
    const pendingTimerIds = [..._saveDebounceTimers.keys()]
    for (const layoutId of pendingTimerIds) {
      const timer = _saveDebounceTimers.get(layoutId)
      if (timer) clearTimeout(timer)
      _saveDebounceTimers.delete(layoutId)
    }

    const dirtyLayoutIds = layouts.value
      .filter((layout) => Boolean(layout.syncFlags?.dirty) || layout.syncFlags?.status === 'local_only')
      .map((layout) => layout.id)

    const uniqueIds = new Set([...pendingTimerIds, ...dirtyLayoutIds])
    let succeeded = 0
    let failed = 0
    for (const layoutId of uniqueIds) {
      const syncReason: 'flush' | 'retry' | 'beforeunload' =
        reason === 'retry' ? 'retry' : (reason === 'beforeunload' ? 'beforeunload' : 'flush')
      const ok = await performSyncLayout(layoutId, syncReason)
      if (ok) succeeded++
      else failed++
    }

    logger.info(`Flush sync complete (${reason}): total=${uniqueIds.size}, ok=${succeeded}, failed=${failed}`)
    return { flushed: uniqueIds.size, succeeded, failed }
  }

  /** Delete layout from server (fire-and-forget, 404 = already gone = OK) */
  async function deleteLayoutFromServer(serverId: string): Promise<void> {
    if (_deleteInFlightServerIds.has(serverId)) {
      logger.debug(`Skip duplicate delete request for server dashboard ${serverId}`)
      return
    }
    _deleteInFlightServerIds.add(serverId)
    try {
      await dashboardsApi.delete(serverId)
      logger.debug(`Deleted layout from server (serverId=${serverId})`)
    } catch (e) {
      if (isHttpStatus(e, 404)) {
        // Dashboard doesn't exist on server — already deleted or never synced. This is fine.
        logger.debug(`Dashboard ${serverId} not found on server — already deleted or never synced`)
      } else {
        logger.warn(`Failed to delete layout from server (serverId=${serverId})`, e)
      }
    } finally {
      _deleteInFlightServerIds.delete(serverId)
    }
  }

  /**
   * Delete multiple layouts at once.
   * Returns the count of actually deleted layouts.
   */
  function bulkDeleteLayouts(layoutIds: string[]): number {
    let deleted = 0
    const serverIdsToDelete = new Set<string>()
    for (const id of layoutIds) {
      const layout = layouts.value.find(l => l.id === id)
      if (!layout) continue
      const serverId = layout.serverId
      const shouldDeleteRemotely = shouldDeleteOnServer(layout)
      layouts.value = layouts.value.filter(l => l.id !== id)
      if (serverId && shouldDeleteRemotely) {
        serverIdsToDelete.add(serverId)
      }
      deleted++
    }
    for (const serverId of serverIdsToDelete) {
      void deleteLayoutFromServer(serverId)
    }
    if (activeLayoutId.value && !layouts.value.find(l => l.id === activeLayoutId.value)) {
      activeLayoutId.value = layouts.value[0]?.id ?? null
    }
    persistLayouts()
    return deleted
  }

  /** Cross-zone dashboards (scope === 'cross-zone', filtered by target.view if set) */
  const crossZoneDashboards = computed(() =>
    layouts.value.filter(l => l.scope === 'cross-zone' && (!l.target || l.target.view === 'monitor'))
  )

  /** Zone dashboards filtered by zoneId */
  function zoneDashboards(zoneId: string): DashboardLayout[] {
    return layouts.value.filter(l => l.scope === 'zone' && l.zoneId === zoneId)
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // TARGET-BASED COMPUTED VIEWS (Phase 4 — Block 7b)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Base filter: monitor + inline placement */
  const _inlineMonitorBase = (l: DashboardLayout) =>
    l.target?.view === 'monitor' && l.target?.placement === 'inline'

  /** Cross-zone inline panels (scope !== 'zone' or scope null) — shown on L1 and L2 */
  const inlineMonitorPanelsCrossZone = computed(() =>
    layouts.value
      .filter(l => _inlineMonitorBase(l) && (l.scope !== 'zone' || l.scope == null))
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Zone-specific inline panels for a given zone — shown only on L2 when zoneId matches */
  function inlineMonitorPanelsForZone(zoneId: string): DashboardLayout[] {
    return layouts.value
      .filter(l => _inlineMonitorBase(l) && l.scope === 'zone' && l.zoneId === zoneId)
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  }

  /** All inline panels for L1 (cross-zone only) — backward compat alias */
  const inlineMonitorPanels = inlineMonitorPanelsCrossZone

  /** Dashboards targeted as side panels in Monitor view */
  const sideMonitorPanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'monitor' && l.target?.placement === 'side-panel')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Dashboards targeted as bottom panels in Monitor view */
  const bottomMonitorPanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'monitor' && l.target?.placement === 'bottom-panel')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Dashboards targeted for display in Hardware view */
  const hardwarePanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'hardware')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Dashboards shown in the Dashboards tab — only explicitly targeted (AUT-841: !l.target removed, JSON null != SQL NULL) */
  const dashboardsTabLayouts = computed(() =>
    layouts.value
      .filter(l => l.target?.view === 'dashboards')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Set display target for a layout. Enforces uniqueness: clears conflicting target from other layouts. */
  function setLayoutTarget(layoutId: string, target: DashboardTarget | null) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return
    const layout = layouts.value[idx]

    // zone-tile dashboards are rendered in Monitor L1 tile context only.
    // They must not participate in target-slot assignment.
    if (layout.scope === 'zone-tile') {
      if (layout.target) {
        applyLayoutPatch(
          layoutId,
          { target: undefined },
          { reasonMessage: 'Zone-Tile nutzt keinen Anzeigeort-Slot' },
        )
      } else if (target) {
        logger.info(`Ignored target assignment for zone-tile layout ${layoutId}`)
      }
      return
    }

    // Enforce target uniqueness: only one dashboard per view+placement slot
    if (target) {
      const existingHolder = layouts.value.find(l =>
        l.id !== layoutId &&
        l.target?.view === target.view &&
        l.target?.placement === target.placement
      )
      if (existingHolder) {
        applyLayoutPatch(
          existingHolder.id,
          { target: undefined },
          { reasonMessage: `Target-Konflikt: Slot von ${layouts.value[idx].name} übernommen` },
        )
        logger.info(`Target conflict: cleared target from "${existingHolder.name}" (replaced by "${layouts.value[idx].name}")`)
      }
    }
    applyLayoutPatch(
      layoutId,
      { target: target || undefined },
      { reasonMessage: target ? 'Anzeigeort aktualisiert' : 'Anzeigeort entfernt' },
    )
  }

  function setLayoutScope(layoutId: string, scope: DashboardScope, zoneId?: string): void {
    applyLayoutPatch(
      layoutId,
      {
        scope,
        zoneId: zoneId || undefined,
      },
      { reasonMessage: `Scope aktualisiert (${scope})` },
    )
  }

  function setLayoutMetadata(
    layoutId: string,
    metadata: Partial<Pick<DashboardLayout, 'scope' | 'zoneId' | 'target' | 'autoGenerated' | 'sensorId' | 'name' | 'description'>>,
  ): void {
    applyLayoutPatch(layoutId, metadata, { reasonMessage: 'Dashboard-Metadaten aktualisiert' })
  }

  /** Retry sync for a specific layout (clears error, re-triggers server sync) */
  function retrySync(layoutId: string): void {
    lastSyncError.value = null
    void performSyncLayout(layoutId, 'retry')
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // WIDGET-LEVEL CRUD (D3/D4)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Add a single widget to an existing layout (auto-generates widget ID) */
  function addWidget(layoutId: string, config: Omit<DashboardWidget, 'id'>): DashboardWidget | null {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return null

    const currentWidgets = (layout.widgets ?? []).map(w => ({
      x: w.x ?? 0, y: w.y ?? 0, w: w.w ?? 1, h: w.h ?? 1,
    }))
    const pos = findFirstFreePosition(
      currentWidgets,
      config.w ?? 6,
      config.h ?? 3
    )

    const widget: DashboardWidget = {
      ...config,
      id: `widget-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      x: pos.x,
      y: pos.y,
    }
    saveLayout(layoutId, [...layout.widgets, widget])
    return widget
  }

  /** Remove a single widget from a layout by widget ID */
  function removeWidget(layoutId: string, widgetId: string): void {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return
    saveLayout(layoutId, layout.widgets.filter(w => w.id !== widgetId))
  }

  /** Partial-update a widget's config within a layout */
  function updateWidgetConfig(layoutId: string, widgetId: string, newConfig: Partial<DashboardWidget['config']>): void {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return
    saveLayout(layoutId, layout.widgets.map(w =>
      w.id === widgetId ? { ...w, config: { ...w.config, ...newConfig } } : w
    ))
  }

  // Auto-load on store creation: localStorage first (instant), then server sync (async)
  loadLayouts()
  fetchLayouts().catch(() => {
    // Error already handled inside fetchLayouts — this prevents unhandled promise rejection
  })

  if (typeof window !== 'undefined') {
    const globalMarker = '__automation_one_dashboard_beforeunload_registered__'
    const win = window as unknown as Record<string, boolean | undefined>
    if (!win[globalMarker]) {
      window.addEventListener('beforeunload', () => {
        void flushPendingSyncs('beforeunload')
      })
      win[globalMarker] = true
    }
  }

  return {
    showControls,
    statusCounts,
    deviceCounts,
    pendingCount,
    activeStatusFilters,
    filterType,
    breadcrumb,
    showCreateMock,
    showPendingPanel,
    navRequestCount,
    navTarget,
    hasProblems,
    problemMessage,
    hasPendingDevices,
    toggleStatusFilter,
    resetFilters,
    activate,
    deactivate,
    requestNavigate,

    // Custom Dashboard Layout (Phase 2 + Phase 3 Server Sync)
    layouts,
    activeLayoutId,
    activeLayout,
    getLayoutById,
    isSyncing,
    syncPending,
    hasFetchedLayouts,
    lastSyncError,
    loadLayouts,
    fetchLayouts,
    createLayout,
    saveLayout,
    deleteLayout,
    exportLayout,
    importLayout,
    crossZoneDashboards,
    zoneDashboards,
    bulkDeleteLayouts,
    getCanonicalZoneTileLayout,

    // Target-based panel views (Phase 4 — Block 7)
    inlineMonitorPanels,
    inlineMonitorPanelsCrossZone,
    inlineMonitorPanelsForZone,
    sideMonitorPanels,
    bottomMonitorPanels,
    hardwarePanels,
    dashboardsTabLayouts,
    setLayoutTarget,
    setLayoutScope,
    setLayoutMetadata,
    retrySync,
    flushPendingSyncs,
    buildLayoutIdentityKey,

    // Widget-level CRUD (D3/D4)
    addWidget,
    removeWidget,
    updateWidgetConfig,
  }
})
