"""
Pydantic Schemas Package

Exports all schema models for API request/response validation.

Phase: 5 (Week 9-10) - API Layer
Status: IMPLEMENTED
"""

# Common schemas
from .common import (
    BaseResponse,
    DataResponse,
    ErrorResponse,
    IDMixin,
    ListResponse,
    PaginatedResponse,
    PaginationMeta,
    PaginationParams,
    SortOrder,
    StatusResponse,
    TimeRangeFilter,
    TimeRangeFilterUnix,
    TimestampMixin,
    ValidationError,
    ValidationErrorResponse,
)

# Auth schemas
from .auth import (
    APIKeyCreate,
    APIKeyInfo,
    APIKeyResponse,
    AuthStatusResponse,
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    LogoutResponse,
    MQTTAuthConfigRequest,
    MQTTAuthConfigResponse,
    MQTTAuthStatusResponse,
    PasswordChangeRequest,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterRequest,
    RegisterResponse,
    SetupRequest,
    SetupResponse,
    TokenResponse,
    UserBase,
    UserResponse,
    UserUpdate,
)

# ESP schemas
from .esp import (
    AssignKaiserRequest,
    AssignKaiserResponse,
    DiscoveredESP,
    ESPApprovalRequest,
    ESPApprovalResponse,
    ESPCommandResponse,
    ESPConfigResponse,
    ESPConfigUpdate,
    ESPDeviceBase,
    ESPDeviceCreate,
    ESPDeviceListResponse,
    ESPDeviceResponse,
    ESPDeviceUpdate,
    ESPDiscoveryResponse,
    ESPHealthMetrics,
    ESPHealthResponse,
    ESPHealthSummary,
    ESPHealthSummaryResponse,
    ESPListFilter,
    ESPRejectionRequest,
    ESPResetRequest,
    ESPRestartRequest,
    PendingDevicesListResponse,
    PendingESPDevice,
)

# Sensor schemas
from .sensor import (
    CalibrationPoint,
    OneWireDevice,
    OneWireScanRequest,
    OneWireScanResponse,
    SensorCalibrateRequest,
    SensorCalibrateResponse,
    SensorConfigBase,
    SensorConfigCreate,
    SensorConfigListResponse,
    SensorConfigResponse,
    SensorConfigUpdate,
    SensorDataPaginatedResponse,
    SensorDataQuery,
    SensorDataResponse,
    SensorListFilter,
    SensorProcessRequest,
    SensorProcessResponse,
    SensorReading,
    SensorStats,
    SensorStatsResponse,
    TriggerMeasurementRequest,
    TriggerMeasurementResponse,
)

# Sensor Type Defaults schemas (Phase 2A)
from .sensor_type_defaults import (
    EffectiveConfigResponse,
    SensorTypeDefaultsCreate,
    SensorTypeDefaultsListResponse,
    SensorTypeDefaultsResponse,
    SensorTypeDefaultsUpdate,
    VALID_OPERATING_MODES,
)

# Actuator schemas
from .actuator import (
    ACTUATOR_COMMANDS,
    ACTUATOR_TYPE_MAPPING,
    ACTUATOR_TYPES,
    ALL_ACTUATOR_TYPES,
    ESP32_ACTUATOR_TYPES,
    ActuatorCommand,
    ActuatorCommandResponse,
    ActuatorConfigBase,
    ActuatorConfigCreate,
    ActuatorConfigListResponse,
    ActuatorConfigResponse,
    ActuatorConfigUpdate,
    ActuatorAggregation,
    ActuatorHistoryEntry,
    ActuatorHistoryResponse,
    ActuatorListFilter,
    ActuatorState,
    ActuatorStatusResponse,
    ClearEmergencyRequest,
    ClearEmergencyResponse,
    EmergencyStopRequest,
    EmergencyStopResponse,
    normalize_actuator_type,
)

# Logic schemas
from .logic import (
    ActionResult,
    ActuatorAction,
    ConditionResult,
    CooldownCondition,
    DelayAction,
    ExecutionHistoryEntry,
    ExecutionHistoryPaginatedResponse,
    ExecutionHistoryQuery,
    ExecutionHistoryResponse,
    LogicRuleBase,
    LogicRuleCreate,
    LogicRuleListResponse,
    LogicRuleResponse,
    LogicRuleUpdate,
    NotificationAction,
    RuleHealthDispatchInfo,
    RuleHealthPayload,
    RuleHealthSkipInfo,
    RuleTestRequest,
    RuleTestResponse,
    RuleToggleRequest,
    RuleToggleResponse,
    SensorCondition,
    TemplateDetailResponse,
    TemplateListResponse,
    TimeCondition,
)

# Zone schemas
from .zone import (
    ZoneAckPayload,
    ZoneAssignRequest,
    ZoneAssignResponse,
    ZoneInfo,
    ZoneRemoveResponse,
)

# Zone entity schemas (Phase 0.3)
from .zone_entity import (
    ZoneCreate,
    ZoneDeleteResponse,
    ZoneListResponse,
    ZoneResponse,
    ZoneUpdate,
)

# Subzone schemas (Phase 9)
from .subzone import (
    SafeModeRequest,
    SafeModeResponse,
    SubzoneAckPayload,
    SubzoneAssignRequest,
    SubzoneAssignResponse,
    SubzoneInfo,
    SubzoneListResponse,
    SubzoneRemoveResponse,
)

# Dashboard schemas
from .dashboard import (
    DashboardCreate,
    DashboardDataResponse,
    DashboardListResponse,
    DashboardResponse,
    DashboardUpdate,
    DashboardWidget,
)

# Notification schemas (Phase 4A.1)
from .notification import (
    NOTIFICATION_CATEGORIES,
    NOTIFICATION_SEVERITIES,
    NOTIFICATION_SOURCES,
    NotificationCreate,
    NotificationListResponse,
    NotificationPreferencesResponse,
    NotificationPreferencesUpdate,
    NotificationResponse,
    NotificationSendRequest,
    NotificationUnreadCountResponse,
    TestEmailRequest,
    TestEmailResponse,
)

# Health schemas
from .health import (
    ComponentHealth,
    DatabaseHealth,
    DetailedHealthResponse,
    ESPHealthItem,
    ESPHealthSummaryResponse as HealthESPSummaryResponse,
    RecentError,
    HealthResponse,
    LivenessResponse,
    MetricsResponse,
    MQTTHealth,
    ReadinessResponse,
    SystemResourceHealth,
    WebSocketHealth,
)

__all__ = [
    # Common
    "BaseResponse",
    "DataResponse",
    "ErrorResponse",
    "IDMixin",
    "ListResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationParams",
    "SortOrder",
    "StatusResponse",
    "TimeRangeFilter",
    "TimeRangeFilterUnix",
    "TimestampMixin",
    "ValidationError",
    "ValidationErrorResponse",
    # Auth
    "APIKeyCreate",
    "APIKeyInfo",
    "APIKeyResponse",
    "AuthStatusResponse",
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "LogoutResponse",
    "MQTTAuthConfigRequest",
    "MQTTAuthConfigResponse",
    "MQTTAuthStatusResponse",
    "PasswordChangeRequest",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RegisterRequest",
    "RegisterResponse",
    "SetupRequest",
    "SetupResponse",
    "TokenResponse",
    "UserBase",
    "UserResponse",
    "UserUpdate",
    # ESP
    "AssignKaiserRequest",
    "AssignKaiserResponse",
    "DiscoveredESP",
    "ESPApprovalRequest",
    "ESPApprovalResponse",
    "ESPCommandResponse",
    "ESPConfigResponse",
    "ESPConfigUpdate",
    "ESPDeviceBase",
    "ESPDeviceCreate",
    "ESPDeviceListResponse",
    "ESPDeviceResponse",
    "ESPDeviceUpdate",
    "ESPDiscoveryResponse",
    "ESPHealthMetrics",
    "ESPHealthResponse",
    "ESPHealthSummary",
    "ESPHealthSummaryResponse",
    "ESPListFilter",
    "ESPRejectionRequest",
    "ESPResetRequest",
    "ESPRestartRequest",
    "PendingDevicesListResponse",
    "PendingESPDevice",
    # Sensor
    "CalibrationPoint",
    "OneWireDevice",
    "OneWireScanRequest",
    "OneWireScanResponse",
    "SensorCalibrateRequest",
    "SensorCalibrateResponse",
    "SensorConfigBase",
    "SensorConfigCreate",
    "SensorConfigListResponse",
    "SensorConfigResponse",
    "SensorConfigUpdate",
    "SensorDataPaginatedResponse",
    "SensorDataQuery",
    "SensorDataResponse",
    "SensorListFilter",
    "SensorProcessRequest",
    "SensorProcessResponse",
    "SensorReading",
    "SensorStats",
    "SensorStatsResponse",
    "TriggerMeasurementRequest",
    "TriggerMeasurementResponse",
    # Sensor Type Defaults (Phase 2A)
    "EffectiveConfigResponse",
    "SensorTypeDefaultsCreate",
    "SensorTypeDefaultsListResponse",
    "SensorTypeDefaultsResponse",
    "SensorTypeDefaultsUpdate",
    "VALID_OPERATING_MODES",
    # Actuator
    "ACTUATOR_COMMANDS",
    "ACTUATOR_TYPE_MAPPING",
    "ACTUATOR_TYPES",
    "ALL_ACTUATOR_TYPES",
    "ESP32_ACTUATOR_TYPES",
    "ActuatorCommand",
    "ActuatorCommandResponse",
    "ActuatorConfigBase",
    "ActuatorConfigCreate",
    "ActuatorConfigListResponse",
    "ActuatorConfigResponse",
    "ActuatorConfigUpdate",
    "ActuatorAggregation",
    "ActuatorHistoryEntry",
    "ActuatorHistoryResponse",
    "ActuatorListFilter",
    "ActuatorState",
    "ActuatorStatusResponse",
    "ClearEmergencyRequest",
    "ClearEmergencyResponse",
    "EmergencyStopRequest",
    "EmergencyStopResponse",
    "normalize_actuator_type",
    # Logic
    "ActionResult",
    "ActuatorAction",
    "ConditionResult",
    "CooldownCondition",
    "DelayAction",
    "ExecutionHistoryEntry",
    "ExecutionHistoryPaginatedResponse",
    "ExecutionHistoryQuery",
    "ExecutionHistoryResponse",
    "LogicRuleBase",
    "LogicRuleCreate",
    "LogicRuleListResponse",
    "LogicRuleResponse",
    "LogicRuleUpdate",
    "NotificationAction",
    "RuleHealthDispatchInfo",
    "RuleHealthPayload",
    "RuleHealthSkipInfo",
    "RuleTestRequest",
    "RuleTestResponse",
    "RuleToggleRequest",
    "RuleToggleResponse",
    "SensorCondition",
    "TemplateDetailResponse",
    "TemplateListResponse",
    "TimeCondition",
    # Zone
    "ZoneAckPayload",
    "ZoneAssignRequest",
    "ZoneAssignResponse",
    "ZoneInfo",
    "ZoneRemoveResponse",
    # Zone Entity (Phase 0.3)
    "ZoneCreate",
    "ZoneDeleteResponse",
    "ZoneListResponse",
    "ZoneResponse",
    "ZoneUpdate",
    # Subzone (Phase 9)
    "SafeModeRequest",
    "SafeModeResponse",
    "SubzoneAckPayload",
    "SubzoneAssignRequest",
    "SubzoneAssignResponse",
    "SubzoneInfo",
    "SubzoneListResponse",
    "SubzoneRemoveResponse",
    # Dashboard
    "DashboardCreate",
    "DashboardDataResponse",
    "DashboardListResponse",
    "DashboardResponse",
    "DashboardUpdate",
    "DashboardWidget",
    # Notification (Phase 4A.1)
    "NOTIFICATION_CATEGORIES",
    "NOTIFICATION_SEVERITIES",
    "NOTIFICATION_SOURCES",
    "NotificationCreate",
    "NotificationListResponse",
    "NotificationPreferencesResponse",
    "NotificationPreferencesUpdate",
    "NotificationResponse",
    "NotificationSendRequest",
    "NotificationUnreadCountResponse",
    "TestEmailRequest",
    "TestEmailResponse",
    # Health
    "ComponentHealth",
    "DatabaseHealth",
    "DetailedHealthResponse",
    "ESPHealthItem",
    "HealthESPSummaryResponse",
    "RecentError",
    "HealthResponse",
    "LivenessResponse",
    "MetricsResponse",
    "MQTTHealth",
    "ReadinessResponse",
    "SystemResourceHealth",
    "WebSocketHealth",
]
