<script setup lang="ts">
/**
 * QuickDashboardPanel — Dashboard catalog sub-panel in the FAB.
 *
 * Shows all dashboards (cross-zone + zone-specific) grouped by scope.
 * Each dashboard has a link to its viewer and an edit button.
 * "Neues Dashboard" button navigates to the editor.
 *
 * Future: drag-to-place functionality for inline/side-panel targets.
 */

import { computed } from 'vue'
import { useRouter } from 'vue-router'
import {
  ArrowLeft,
  LayoutDashboard,
  Pencil,
  Plus,
  Sparkles,
} from 'lucide-vue-next'
import { useQuickActionStore } from '@/shared/stores/quickAction.store'
import { useDashboardStore, type DashboardLayout } from '@/shared/stores/dashboard.store'

const router = useRouter()
const quickActionStore = useQuickActionStore()
const dashStore = useDashboardStore()

/** All dashboards grouped: cross-zone first, then zone-specific */
const crossZoneDashboards = computed(() => dashStore.crossZoneDashboards)

const zoneDashboardGroups = computed(() => {
  const groups = new Map<string, { zoneName: string; dashboards: DashboardLayout[] }>()
  for (const layout of dashStore.layouts) {
    if (layout.scope !== 'zone' || !layout.zoneId) continue
    if (!groups.has(layout.zoneId)) {
      groups.set(layout.zoneId, { zoneName: layout.name.replace(' Dashboard', '') || layout.zoneId, dashboards: [] })
    }
    groups.get(layout.zoneId)!.dashboards.push(layout)
  }
  return Array.from(groups.values())
})

const hasDashboards = computed(() =>
  crossZoneDashboards.value.length > 0 || zoneDashboardGroups.value.length > 0
)

function handleBack(): void {
  quickActionStore.setActivePanel('menu')
}

function navigateToDashboard(dashboardId: string): void {
  void router.push({ name: 'editor-dashboard', params: { dashboardId } })
  quickActionStore.closeMenu()
}

function navigateToEditor(dashboardId?: string): void {
  if (dashboardId) {
    void router.push({ name: 'editor-dashboard', params: { dashboardId } })
  } else {
    void router.push({ name: 'editor' })
  }
  quickActionStore.closeMenu()
}
</script>

<template>
  <div class="qa-dash-panel" role="region" aria-label="Dashboard-Hub">
    <!-- Header -->
    <div class="qa-dash-panel__header">
      <button
        class="qa-dash-panel__back"
        aria-label="Zurueck zum Menu"
        @click="handleBack"
      >
        <ArrowLeft class="qa-dash-panel__back-icon" />
      </button>
      <LayoutDashboard class="qa-dash-panel__header-icon" />
      <span class="qa-dash-panel__title">Dashboards</span>
      <button
        class="qa-dash-panel__new-btn"
        title="Neues Dashboard erstellen"
        @click="navigateToEditor()"
      >
        <Plus :size="14" />
      </button>
    </div>

    <!-- Empty State -->
    <div v-if="!hasDashboards" class="qa-dash-panel__empty">
      <LayoutDashboard class="qa-dash-panel__empty-icon" />
      <p class="qa-dash-panel__empty-text">Noch keine Dashboards erstellt.</p>
      <button class="qa-dash-panel__empty-btn" @click="navigateToEditor()">
        <Plus :size="12" />
        Dashboard erstellen
      </button>
    </div>

    <!-- Dashboard List -->
    <div v-else class="qa-dash-panel__list">
      <!-- Cross-Zone Dashboards -->
      <template v-if="crossZoneDashboards.length > 0">
        <span class="qa-dash-panel__group-label">Cross-Zone</span>
        <div
          v-for="dash in crossZoneDashboards"
          :key="dash.id"
          class="qa-dash-panel__item"
        >
          <button
            class="qa-dash-panel__item-link"
            @click="navigateToDashboard(dash.id)"
          >
            <LayoutDashboard class="qa-dash-panel__item-icon" />
            <div class="qa-dash-panel__item-text">
              <span class="qa-dash-panel__item-name">{{ dash.name }}</span>
              <span class="qa-dash-panel__item-meta">
                {{ dash.widgets.length }} Widgets
                <Sparkles v-if="dash.autoGenerated" class="qa-dash-panel__auto-icon" />
              </span>
            </div>
          </button>
          <button
            class="qa-dash-panel__item-edit"
            title="Im Editor bearbeiten"
            @click.stop="navigateToEditor(dash.serverId || dash.id)"
          >
            <Pencil :size="12" />
          </button>
        </div>
      </template>

      <!-- Zone-Specific Dashboards -->
      <template v-for="group in zoneDashboardGroups" :key="group.zoneName">
        <span class="qa-dash-panel__group-label">{{ group.zoneName }}</span>
        <div
          v-for="dash in group.dashboards"
          :key="dash.id"
          class="qa-dash-panel__item"
        >
          <button
            class="qa-dash-panel__item-link"
            @click="navigateToDashboard(dash.id)"
          >
            <LayoutDashboard class="qa-dash-panel__item-icon" />
            <div class="qa-dash-panel__item-text">
              <span class="qa-dash-panel__item-name">{{ dash.name }}</span>
              <span class="qa-dash-panel__item-meta">
                {{ dash.widgets.length }} Widgets
                <Sparkles v-if="dash.autoGenerated" class="qa-dash-panel__auto-icon" />
              </span>
            </div>
          </button>
          <button
            class="qa-dash-panel__item-edit"
            title="Im Editor bearbeiten"
            @click.stop="navigateToEditor(dash.serverId || dash.id)"
          >
            <Pencil :size="12" />
          </button>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
/* ═══════════════════════════════════════════════════════════════════════════
   QUICK DASHBOARD PANEL — Dashboard catalog sub-panel
   ═══════════════════════════════════════════════════════════════════════════ */

.qa-dash-panel {
  position: fixed;
  bottom: calc(64px + var(--space-2));
  right: 20px;
  width: 280px;
  min-height: 120px;
  max-height: 60vh;
  display: flex;
  flex-direction: column;
  background: rgba(20, 20, 30, 0.92);
  -webkit-backdrop-filter: blur(16px);
  backdrop-filter: blur(16px);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--elevation-floating);
  z-index: var(--z-fab);
  overflow: hidden;
}

/* ── Header ── */

.qa-dash-panel__header {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-3);
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}

.qa-dash-panel__back {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: var(--radius-sm);
  border: none;
  background: transparent;
  color: var(--color-text-secondary);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.qa-dash-panel__back:hover {
  background: rgba(255, 255, 255, 0.08);
  color: var(--color-text-primary);
}

.qa-dash-panel__back-icon {
  width: 14px;
  height: 14px;
}

.qa-dash-panel__header-icon {
  width: 16px;
  height: 16px;
  color: var(--color-iridescent-2);
}

.qa-dash-panel__title {
  font-size: var(--text-sm);
  font-weight: 600;
  color: var(--color-text-primary);
  flex: 1;
}

.qa-dash-panel__new-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: var(--radius-sm);
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.04);
  color: var(--color-text-secondary);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.qa-dash-panel__new-btn:hover {
  background: rgba(96, 165, 250, 0.12);
  border-color: rgba(96, 165, 250, 0.25);
  color: var(--color-iridescent-1);
}

/* ── Empty State ── */

.qa-dash-panel__empty {
  padding: var(--space-6) var(--space-4);
  text-align: center;
  min-height: 120px;
}

.qa-dash-panel__empty-icon {
  width: 32px;
  height: 32px;
  color: var(--color-text-muted);
  opacity: 0.4;
  margin: 0 auto var(--space-3);
}

.qa-dash-panel__empty-text {
  font-size: var(--text-xs);
  color: var(--color-text-muted);
  margin: 0 0 var(--space-3);
}

.qa-dash-panel__empty-btn {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  font-size: var(--text-xs);
  font-weight: 500;
  color: var(--color-accent);
  background: rgba(96, 165, 250, 0.1);
  border: 1px solid rgba(96, 165, 250, 0.2);
  border-radius: var(--radius-sm);
  padding: var(--space-1) var(--space-3);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.qa-dash-panel__empty-btn:hover {
  background: rgba(96, 165, 250, 0.2);
  border-color: rgba(96, 165, 250, 0.3);
}

/* ── Dashboard List ── */

.qa-dash-panel__list {
  flex: 1;
  overflow-y: auto;
  padding: var(--space-1);
}

.qa-dash-panel__group-label {
  display: block;
  font-size: var(--text-xxs);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--color-text-muted);
  opacity: 0.6;
  padding: var(--space-2) var(--space-2) var(--space-1);
}

/* ── Dashboard Item ── */

.qa-dash-panel__item {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  padding: 0 var(--space-1) 0 0;
  border-radius: var(--radius-sm);
  transition: background var(--transition-fast);
}

.qa-dash-panel__item:hover {
  background: rgba(255, 255, 255, 0.04);
}

.qa-dash-panel__item-link {
  flex: 1;
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2);
  border: none;
  background: transparent;
  color: inherit;
  cursor: pointer;
  min-width: 0;
  text-align: left;
}

.qa-dash-panel__item-icon {
  flex-shrink: 0;
  width: 14px;
  height: 14px;
  color: var(--color-iridescent-2);
}

.qa-dash-panel__item-text {
  flex: 1;
  min-width: 0;
}

.qa-dash-panel__item-name {
  display: block;
  font-size: var(--text-xs);
  font-weight: 500;
  color: var(--color-text-primary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.qa-dash-panel__item-meta {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  font-size: var(--text-xxs);
  color: var(--color-text-muted);
}

.qa-dash-panel__auto-icon {
  width: 10px;
  height: 10px;
  color: var(--color-iridescent-3);
}

.qa-dash-panel__item-edit {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: var(--radius-sm);
  border: none;
  background: transparent;
  color: var(--color-text-muted);
  cursor: pointer;
  opacity: 0;
  transition: all var(--transition-fast);
}

.qa-dash-panel__item:hover .qa-dash-panel__item-edit {
  opacity: 1;
}

.qa-dash-panel__item-edit:hover {
  background: rgba(255, 255, 255, 0.08);
  color: var(--color-iridescent-1);
}

/* ═══ TOUCH DEVICES ════════════════════════════════════════════════════════ */

@media (hover: none) {
  .qa-dash-panel__item-edit {
    opacity: 1;
  }
}

/* ═══ REDUCED MOTION ═══════════════════════════════════════════════════════ */

@media (prefers-reduced-motion: reduce) {
  .qa-dash-panel__item,
  .qa-dash-panel__back,
  .qa-dash-panel__new-btn,
  .qa-dash-panel__empty-btn,
  .qa-dash-panel__item-edit {
    transition: none;
  }
}
</style>
