"""
Request-Context for request_id / correlation_id tracking.

Uses contextvars to pass request_id through all layers
without explicit parameter passing.

Two ID types coexist:
- REST requests: UUID (generated by RequestIdMiddleware or received via X-Request-ID header)
- MQTT messages: Human-readable format {esp_id}:{topic_suffix}:{seq}:{timestamp_ms}

Optional W3C **traceparent** (HTTP header) is stored separately when present on REST/WebSocket
requests — for logging and outbound header echo. Not used for MQTT.
"""

import contextvars
import time
from typing import Optional, Union
import uuid

_request_id_ctx: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "request_id", default=None
)
_correlation_id_ctx: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "correlation_id", default=None
)

_traceparent_ctx: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "traceparent", default=None
)

# W3C Trace Context: header value should be <= 255 chars
_MAX_TRACEPARENT_LEN = 255


def get_request_id() -> Optional[str]:
    """Return the current request_id (or None)."""
    return _request_id_ctx.get()


def set_request_id(request_id: str) -> contextvars.Token:
    """Set the request_id for the current context.

    Returns token for proper cleanup via clear_request_id(token).
    Backwards-compatible: callers that ignore the return value still work.
    """
    return _request_id_ctx.set(request_id)


def generate_request_id() -> str:
    """Generate a new UUID request_id (for REST requests)."""
    return str(uuid.uuid4())


def generate_mqtt_correlation_id(esp_id: str, topic_suffix: str, seq: Union[int, str, None]) -> str:
    """Generate human-readable correlation ID for MQTT messages.

    Format: {esp_id}:{topic_suffix}:{seq}:{timestamp_ms}
    Example: ESP_12AB34CD:data:142:1708704000000

    Args:
        esp_id: ESP device identifier (from payload or topic)
        topic_suffix: Last segment of MQTT topic (e.g. "data", "heartbeat")
        seq: Sequence number from ESP32 payload (None if absent)

    Returns:
        Correlation ID string for cross-layer tracing
    """
    ts_ms = int(time.time() * 1000)
    seq_part = str(seq) if seq is not None else "no-seq"
    return f"{esp_id}:{topic_suffix}:{seq_part}:{ts_ms}"


def build_emergency_actuator_correlation_id(
    incident_correlation_id: str, esp_id: str, gpio: int
) -> str:
    """Deterministic MQTT correlation_id for one emergency OFF publish per GPIO.

    Format matches other server correlation strings (colon-separated, JSON-safe).
    Maps one-to-one to ``incident_correlation_id`` in audit/WS for E2E support queries.

    Args:
        incident_correlation_id: UUID string for the whole emergency incident
        esp_id: Device id (e.g. ESP_…)
        gpio: Target GPIO for this publish

    Returns:
        Single string passed to ``Publisher.publish_actuator_command(..., correlation_id=…)``.
    """
    return f"{incident_correlation_id}:{esp_id}:{gpio}"


def get_correlation_id() -> Optional[str]:
    """Return the current correlation_id (or None)."""
    return _correlation_id_ctx.get()


def set_correlation_id(correlation_id: str) -> contextvars.Token:
    """Set the correlation_id for the current context.

    Returns token for proper cleanup via clear_correlation_id(token).
    Backwards-compatible: callers that ignore the return value still work.
    """
    return _correlation_id_ctx.set(correlation_id)


def clear_correlation_id(token: Optional[contextvars.Token] = None) -> None:
    """Clear the correlation_id from context.

    Args:
        token: If provided, resets ContextVar to the state before set_correlation_id().
               If None, sets the value to None (backwards-compatible fallback).
    """
    if token is not None:
        _correlation_id_ctx.reset(token)
    else:
        _correlation_id_ctx.set(None)


def clear_request_id(token: Optional[contextvars.Token] = None) -> None:
    """Clear the request_id from context.

    Args:
        token: If provided, resets ContextVar to the state before set_request_id().
               If None, sets the value to None (backwards-compatible fallback).
    """
    if token is not None:
        _request_id_ctx.reset(token)
    else:
        _request_id_ctx.set(None)


def get_traceparent() -> Optional[str]:
    """Return the current W3C traceparent header value (or None if unset)."""
    return _traceparent_ctx.get()


def set_traceparent(traceparent: Optional[str]) -> contextvars.Token:
    """Set traceparent for the current context. Use None when absent.

    Values longer than 255 characters are rejected (returns token with None stored)
    to avoid oversized headers in logs/responses.
    """
    if traceparent is not None:
        stripped = traceparent.strip()
        if not stripped or len(stripped) > _MAX_TRACEPARENT_LEN:
            traceparent = None
        else:
            traceparent = stripped
    return _traceparent_ctx.set(traceparent)


def clear_traceparent(token: Optional[contextvars.Token] = None) -> None:
    """Reset traceparent ContextVar (prefer *token* from set_traceparent)."""
    if token is not None:
        _traceparent_ctx.reset(token)
    else:
        _traceparent_ctx.set(None)
