"""
Server-side Error Code Enrichment — analogous to esp32_error_mapping.py

Maps Server error codes (5000-5999) to rich metadata for frontend
troubleshooting display. Each entry mirrors the ESP32 enrichment schema:
- category: Functional area
- severity: critical/error/warning/info
- message_de: Technical German message for logs
- message_user_de: User-friendly German message for UI
- troubleshooting_de: List of troubleshooting steps
- docs_link: Link to documentation (if available)
- recoverable: Whether the system can self-recover
- user_action_required: Whether user intervention is needed

IMPORTANT: esp32_error_mapping.py is 111/111 complete — DO NOT TOUCH.
This file covers SERVER codes only (5000-5999).
"""

from typing import Any, Dict, Optional

SERVER_ERROR_MAPPING: Dict[int, Dict[str, Any]] = {
    # =========================================================================
    # Config Errors (5000-5099)
    # =========================================================================
    5001: {
        "category": "DEVICE",
        "severity": "error",
        "message_de": "ESP32-Geraet nicht gefunden",
        "message_user_de": "Das Geraet wurde nicht gefunden. Bitte ID pruefen.",
        "troubleshooting_de": [
            "ESP-ID in der HardwareView pruefen",
            "Geraet wurde moeglicherweise geloescht oder nie registriert",
            "Bei Neuzugang: Geraet zuerst mit dem System verbinden",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5002: {
        "category": "CONFIG",
        "severity": "error",
        "message_de": "Konfigurationserstellung fehlgeschlagen",
        "message_user_de": "Die Geraetekonfiguration konnte nicht erstellt werden.",
        "troubleshooting_de": [
            "Konfigurationsfelder auf Vollstaendigkeit pruefen",
            "Server-Logs auf detaillierte Fehlermeldung pruefen",
            "Geraet erneut konfigurieren",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5003: {
        "category": "CONFIG",
        "severity": "error",
        "message_de": "Konfigurations-Payload ungueltig",
        "message_user_de": "Die gesendete Konfiguration ist ungueltig.",
        "troubleshooting_de": [
            "Eingabefelder auf korrekte Werte pruefen",
            "GPIO-Pins auf Konflikte pruefen",
            "Sensortyp und Interface muessen zusammenpassen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5004: {
        "category": "CONFIG",
        "severity": "error",
        "message_de": "Konfiguration konnte nicht via MQTT publiziert werden",
        "message_user_de": "Die Konfiguration konnte nicht an das Geraet gesendet werden.",
        "troubleshooting_de": [
            "MQTT-Broker-Verbindung pruefen",
            "ESP-Geraet muss online sein",
            "Netzwerkverbindung zwischen Server und Broker pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5005: {
        "category": "CONFIG",
        "severity": "error",
        "message_de": "Feld-Mapping fehlgeschlagen",
        "message_user_de": "Interner Fehler bei der Konfigurationsumwandlung.",
        "troubleshooting_de": [
            "Server-Logs pruefen fuer Details",
            "Konfiguration erneut senden",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5006: {
        "category": "CONFIG",
        "severity": "warning",
        "message_de": "Konfigurationsantwort Timeout",
        "message_user_de": "Das Geraet hat nicht rechtzeitig auf die Konfiguration geantwortet.",
        "troubleshooting_de": [
            "Pruefen ob das Geraet online ist",
            "MQTT-Verbindung des Geraets pruefen",
            "Konfiguration erneut senden",
            "Bei wiederholtem Timeout: Geraet neustarten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5007: {
        "category": "DEVICE",
        "severity": "warning",
        "message_de": "ESP-Geraet ist offline",
        "message_user_de": "Das Geraet ist derzeit nicht erreichbar.",
        "troubleshooting_de": [
            "Stromversorgung des Geraets pruefen",
            "WiFi-Verbindung pruefen",
            "Geraet neustarten",
            "Heartbeat-Status in der HardwareView pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5008: {
        "category": "DEVICE",
        "severity": "error",
        "message_de": "ESP32-Befehlsausfuehrung fehlgeschlagen",
        "message_user_de": "Der Befehl an das Geraet konnte nicht ausgefuehrt werden.",
        "troubleshooting_de": [
            "Geraetestatus pruefen (online/offline)",
            "Befehl erneut senden",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    # =========================================================================
    # MQTT Errors (5100-5199)
    # =========================================================================
    5101: {
        "category": "MQTT",
        "severity": "error",
        "message_de": "MQTT Publish fehlgeschlagen",
        "message_user_de": "Nachricht konnte nicht an den MQTT-Broker gesendet werden.",
        "troubleshooting_de": [
            "MQTT-Broker-Status pruefen (docker ps)",
            "Netzwerkverbindung pruefen",
            "Server-Logs auf MQTT-Fehler pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5104: {
        "category": "MQTT",
        "severity": "critical",
        "message_de": "MQTT-Verbindung verloren",
        "message_user_de": "Die Verbindung zum MQTT-Broker wurde unterbrochen.",
        "troubleshooting_de": [
            "MQTT-Broker-Container pruefen: docker ps | grep mqtt",
            "Broker-Logs pruefen: docker logs mqtt-broker",
            "Netzwerk zwischen Server und Broker pruefen",
            "Server wird automatisch reconnecten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5106: {
        "category": "MQTT",
        "severity": "critical",
        "message_de": "MQTT-Broker nicht erreichbar",
        "message_user_de": "Der MQTT-Broker ist nicht verfuegbar.",
        "troubleshooting_de": [
            "MQTT-Broker-Container starten: docker compose up -d mqtt-broker",
            "Port 1883 pruefen",
            "Firewall-Regeln pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5108: {
        "category": "MQTT",
        "severity": "error",
        "message_de": "MQTT Subscribe fehlgeschlagen",
        "message_user_de": "Topic-Abonnement konnte nicht eingerichtet werden.",
        "troubleshooting_de": [
            "MQTT-Broker-Verbindung pruefen",
            "Topic-Name auf Korrektheit pruefen",
            "Broker-ACL-Konfiguration pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    # =========================================================================
    # Validation Errors (5200-5299)
    # =========================================================================
    5201: {
        "category": "VALIDATION",
        "severity": "warning",
        "message_de": "Ungueltiges ESP-ID-Format",
        "message_user_de": "Die eingegebene Geraete-ID hat ein ungueltiges Format.",
        "troubleshooting_de": [
            "ESP-ID muss dem Format ESP_XXXXXXXX entsprechen",
            "Nur Grossbuchstaben und Ziffern nach dem Praefix",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5205: {
        "category": "VALIDATION",
        "severity": "warning",
        "message_de": "Pflichtfeld fehlt in der Anfrage",
        "message_user_de": "Ein erforderliches Feld wurde nicht ausgefuellt.",
        "troubleshooting_de": [
            "Alle Pflichtfelder im Formular ausfuellen",
            "Fehlermeldung zeigt welches Feld fehlt",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5208: {
        "category": "VALIDATION",
        "severity": "warning",
        "message_de": "Doppelter Eintrag",
        "message_user_de": "Ein Eintrag mit diesen Daten existiert bereits.",
        "troubleshooting_de": [
            "Pruefen ob die Ressource bereits existiert",
            "Bestehenden Eintrag bearbeiten statt neu erstellen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5210: {
        "category": "VALIDATION",
        "severity": "error",
        "message_de": "Sensor nicht in Server-Datenbank gefunden",
        "message_user_de": "Der angeforderte Sensor wurde nicht gefunden.",
        "troubleshooting_de": [
            "Sensor-Konfiguration des ESP-Geraets pruefen",
            "GPIO-Pin und ESP-ID ueberpruefen",
            "Sensor muss zuerst konfiguriert werden",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5211: {
        "category": "VALIDATION",
        "severity": "error",
        "message_de": "Aktor nicht in Server-Datenbank gefunden",
        "message_user_de": "Der angeforderte Aktor wurde nicht gefunden.",
        "troubleshooting_de": [
            "Aktor-Konfiguration des ESP-Geraets pruefen",
            "GPIO-Pin und ESP-ID ueberpruefen",
            "Aktor muss zuerst konfiguriert werden",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # Database Errors (5300-5399)
    # =========================================================================
    5301: {
        "category": "DATABASE",
        "severity": "error",
        "message_de": "Datenbankabfrage fehlgeschlagen",
        "message_user_de": "Interner Datenbankfehler. Bitte erneut versuchen.",
        "troubleshooting_de": [
            "PostgreSQL-Container pruefen: docker ps | grep postgres",
            "Datenbank-Logs pruefen: docker logs postgres",
            "Anfrage erneut senden",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5304: {
        "category": "DATABASE",
        "severity": "critical",
        "message_de": "Datenbankverbindung fehlgeschlagen",
        "message_user_de": "Keine Verbindung zur Datenbank moeglich.",
        "troubleshooting_de": [
            "PostgreSQL-Container starten: docker compose up -d postgres",
            "Datenbankverbindungsdaten pruefen (.env)",
            "Port 5432 pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5305: {
        "category": "DATABASE",
        "severity": "error",
        "message_de": "Datenbank-Integritaetsfehler",
        "message_user_de": "Datenkonsistenzpruefung fehlgeschlagen (z.B. doppelter Eintrag).",
        "troubleshooting_de": [
            "Pruefen ob die Daten bereits existieren",
            "Unique-Constraints in der Datenbank pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5307: {
        "category": "DATABASE",
        "severity": "error",
        "message_de": "Datensatz nicht gefunden",
        "message_user_de": "Der angeforderte Datensatz existiert nicht.",
        "troubleshooting_de": [
            "ID oder Suchkriterien pruefen",
            "Datensatz wurde moeglicherweise geloescht",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5308: {
        "category": "DATABASE",
        "severity": "warning",
        "message_de": "Doppelter Datensatz",
        "message_user_de": "Ein Datensatz mit diesen Werten existiert bereits.",
        "troubleshooting_de": [
            "Bestehenden Datensatz bearbeiten statt neuen erstellen",
            "Eindeutige Felder pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    # =========================================================================
    # Service Errors (5400-5499)
    # =========================================================================
    5401: {
        "category": "SERVICE",
        "severity": "critical",
        "message_de": "Service-Initialisierung fehlgeschlagen",
        "message_user_de": "Ein interner Service konnte nicht gestartet werden.",
        "troubleshooting_de": [
            "Server-Logs pruefen",
            "Abhaengige Services pruefen (MQTT, DB)",
            "Server neustarten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5403: {
        "category": "SERVICE",
        "severity": "warning",
        "message_de": "Service-Operation Timeout",
        "message_user_de": "Die Operation hat zu lange gedauert und wurde abgebrochen.",
        "troubleshooting_de": [
            "Vorgang erneut versuchen",
            "Bei wiederholtem Timeout: Systemlast pruefen",
            "Netzwerkverbindung pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5405: {
        "category": "SERVICE",
        "severity": "warning",
        "message_de": "Zugriff verweigert",
        "message_user_de": "Sie haben keine Berechtigung fuer diese Aktion.",
        "troubleshooting_de": [
            "Anmeldestatus pruefen",
            "Admin-Rechte fuer diese Aktion erforderlich",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5406: {
        "category": "AUTH",
        "severity": "warning",
        "message_de": "Authentifizierung fehlgeschlagen",
        "message_user_de": "Benutzername oder Passwort ist falsch.",
        "troubleshooting_de": [
            "Benutzername und Passwort pruefen",
            "Gross-/Kleinschreibung beachten",
            "Bei gesperrtem Konto: Administrator kontaktieren",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5407: {
        "category": "AUTH",
        "severity": "info",
        "message_de": "Authentifizierungstoken abgelaufen",
        "message_user_de": "Ihre Sitzung ist abgelaufen. Bitte erneut anmelden.",
        "troubleshooting_de": [
            "Seite neu laden — automatischer Token-Refresh",
            "Falls weiterhin: Erneut anmelden",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5408: {
        "category": "AUTH",
        "severity": "warning",
        "message_de": "Ungueltiger Authentifizierungstoken",
        "message_user_de": "Ihre Anmeldung ist ungueltig. Bitte erneut anmelden.",
        "troubleshooting_de": [
            "Erneut anmelden",
            "Browser-Cache leeren falls Problem fortbesteht",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5409: {
        "category": "AUTH",
        "severity": "warning",
        "message_de": "Autorisierung fehlgeschlagen",
        "message_user_de": "Keine ausreichenden Berechtigungen fuer diese Aktion.",
        "troubleshooting_de": [
            "Admin-Rechte erforderlich",
            "Administrator fuer Berechtigungserweiterung kontaktieren",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5410: {
        "category": "SERVICE",
        "severity": "error",
        "message_de": "Externer Service nicht verfuegbar",
        "message_user_de": "Ein externer Service ist derzeit nicht erreichbar.",
        "troubleshooting_de": [
            "Service-Status pruefen",
            "Netzwerkverbindung pruefen",
            "Spaeter erneut versuchen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5411: {
        "category": "SENSOR",
        "severity": "error",
        "message_de": "Sensor-Datenverarbeitung fehlgeschlagen",
        "message_user_de": "Sensordaten konnten nicht verarbeitet werden.",
        "troubleshooting_de": [
            "Sensor-Rohdaten pruefen",
            "Sensor-Konfiguration ueberpruefen",
            "ESP-Geraet pruefen ob Sensor korrekt angeschlossen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5412: {
        "category": "ACTUATOR",
        "severity": "error",
        "message_de": "Aktor-Befehlsausfuehrung fehlgeschlagen",
        "message_user_de": "Der Befehl an den Aktor konnte nicht ausgefuehrt werden.",
        "troubleshooting_de": [
            "Aktor-Status pruefen",
            "ESP-Geraet muss online sein",
            "GPIO-Pin und Verkabelung pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5413: {
        "category": "SAFETY",
        "severity": "critical",
        "message_de": "Sicherheitsregel verletzt",
        "message_user_de": "Die Aktion wurde durch eine Sicherheitsregel blockiert.",
        "troubleshooting_de": [
            "Sicherheitsregeln im System pruefen",
            "Aktuelle Grenzwerte in der Logic-Engine pruefen",
            "Bei berechtigtem Bedarf: Regel anpassen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5414: {
        "category": "AUTH",
        "severity": "error",
        "message_de": "Benutzer nicht gefunden",
        "message_user_de": "Der angegebene Benutzer existiert nicht.",
        "troubleshooting_de": [
            "Benutzername pruefen",
            "Benutzer muss zuerst registriert werden",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # External Service / Audit Errors (5500-5599)
    # =========================================================================
    5500: {
        "category": "EXTERNAL_SERVICE",
        "severity": "error",
        "message_de": "Externer Service nicht erreichbar",
        "message_user_de": "Externer Dienst nicht erreichbar",
        "troubleshooting_de": [
            "Service-Status pruefen",
            "Netzwerkverbindung pruefen",
            "Spaeter erneut versuchen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5501: {
        "category": "EXTERNAL_SERVICE",
        "severity": "error",
        "message_de": "Externer Service Timeout",
        "message_user_de": "Externer Dienst antwortet nicht",
        "troubleshooting_de": [
            "Service-Erreichbarkeit pruefen",
            "Timeout-Konfiguration pruefen",
            "Spaeter erneut versuchen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5502: {
        "category": "EXTERNAL_SERVICE",
        "severity": "critical",
        "message_de": "Externer Service Authentifizierung fehlgeschlagen",
        "message_user_de": "Externer Dienst: Authentifizierung fehlgeschlagen",
        "troubleshooting_de": [
            "API-Zugangsdaten pruefen",
            "Token-Gueltigkeit pruefen",
            "Provider-Konfiguration ueberpruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5503: {
        "category": "EXTERNAL_SERVICE",
        "severity": "warning",
        "message_de": "Externer Service Rate-Limit erreicht",
        "message_user_de": "Externer Dienst: Rate-Limit erreicht",
        "troubleshooting_de": [
            "Anfragen reduzieren",
            "Rate-Limit-Fenster abwarten",
            "API-Kontingent beim Provider pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5504: {
        "category": "EXTERNAL_SERVICE",
        "severity": "error",
        "message_de": "Externer Service ungueltige Antwort",
        "message_user_de": "Externer Dienst: Ungueltige Antwort",
        "troubleshooting_de": [
            "Service-Logs auf Fehler pruefen",
            "API-Version und Kompatibilitaet pruefen",
            "Provider-Status-Seite pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": False,
    },
    5505: {
        "category": "EXTERNAL_SERVICE",
        "severity": "error",
        "message_de": "Externer Service Verbindungsfehler",
        "message_user_de": "Externer Dienst: Verbindungsfehler",
        "troubleshooting_de": [
            "Netzwerkverbindung pruefen",
            "Firewall-Regeln pruefen",
            "Spaeter erneut versuchen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5506: {
        "category": "EXTERNAL_SERVICE",
        "severity": "warning",
        "message_de": "Audit-Log schreiben fehlgeschlagen",
        "message_user_de": "Audit-Log konnte nicht geschrieben werden",
        "troubleshooting_de": [
            "Schreibberechtigungen pruefen",
            "Speicherkapazitaet pruefen",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5507: {
        "category": "EXTERNAL_SERVICE",
        "severity": "info",
        "message_de": "Audit-Log lesen fehlgeschlagen",
        "message_user_de": "Audit-Log konnte nicht gelesen werden",
        "troubleshooting_de": [
            "Leseberechtigungen pruefen",
            "Audit-Log-Pfad pruefen",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    # =========================================================================
    # Sequence Errors (5600-5699) — most common
    # =========================================================================
    5600: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Definition ungueltig",
        "message_user_de": "Die Sequenzkonfiguration ist ungueltig",
        "troubleshooting_de": [
            "Sequenz-Definition pruefen",
            "Alle Pflichtfelder ausfuellen",
            "Schritte auf korrekte Konfiguration pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5601: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz hat keine Schritte",
        "message_user_de": "Sequenz muss mindestens einen Schritt enthalten",
        "troubleshooting_de": [
            "Mindestens einen Schritt zur Sequenz hinzufuegen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5602: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Schritt ungueltig",
        "message_user_de": "Ein Sequenz-Schritt ist ungueltig konfiguriert",
        "troubleshooting_de": [
            "Schrittkonfiguration pruefen",
            "Aktionstyp und Felder ueberpruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5603: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Unbekannter Aktionstyp in Sequenz-Schritt",
        "message_user_de": "Unbekannter Aktionstyp im Sequenz-Schritt",
        "troubleshooting_de": [
            "Gueltigen Aktionstyp verwenden",
            "Verfuegbare Aktionstypen pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5604: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Schritt ohne Aktion oder Verzoegerung",
        "message_user_de": "Jeder Schritt muss eine Aktion oder Verzoegerung enthalten",
        "troubleshooting_de": [
            "Jedem Schritt eine Aktion oder delay_seconds zuweisen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5605: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Ungueltige Verzoegerung in Sequenz-Schritt",
        "message_user_de": "Verzoegerungswert ungueltig (0-3600 Sekunden erlaubt)",
        "troubleshooting_de": [
            "Verzoegerungswert auf gueltigen Bereich 0-3600 Sekunden setzen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5606: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Zu viele Schritte in der Sequenz",
        "message_user_de": "Sequenz ueberschreitet die maximale Schrittanzahl (50)",
        "troubleshooting_de": [
            "Schritte auf maximal 50 reduzieren",
            "Grosse Sequenzen in mehrere aufteilen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5607: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Gesamtdauer ueberschritten",
        "message_user_de": "Sequenz ueberschreitet die maximale Ausfuehrungsdauer",
        "troubleshooting_de": [
            "Sequenz-Dauer reduzieren",
            "Lange Schritte aufteilen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5610: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz laeuft bereits",
        "message_user_de": "Eine Sequenz mit dieser ID laeuft bereits",
        "troubleshooting_de": [
            "Laufende Sequenz abwarten",
            "Aktive Sequenzen pruefen: GET /api/v1/sequences/running",
            "Laufende Sequenz stoppen falls noetig",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5611: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz nicht gefunden",
        "message_user_de": "Die angeforderte Sequenz existiert nicht.",
        "troubleshooting_de": [
            "Sequenz-ID pruefen",
            "Sequenz wurde moeglicherweise geloescht",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5612: {
        "category": "SEQUENCE",
        "severity": "info",
        "message_de": "Sequenz abgebrochen",
        "message_user_de": "Die Sequenz wurde abgebrochen",
        "troubleshooting_de": [
            "Sequenz bei Bedarf erneut starten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5613: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz Timeout",
        "message_user_de": "Sequenz: Zeitüberschreitung",
        "troubleshooting_de": [
            "Sequenz-Dauer pruefen",
            "ESP-Geraete auf Erreichbarkeit pruefen",
            "Sequenz erneut starten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5614: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Schritt Ausfuehrung fehlgeschlagen",
        "message_user_de": "Ein Sequenz-Schritt ist fehlgeschlagen",
        "troubleshooting_de": [
            "Schrittkonfiguration pruefen",
            "Aktor-Status pruefen",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5615: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz-Schritt Timeout",
        "message_user_de": "Ein Sequenz-Schritt hat die Zeitgrenze ueberschritten",
        "troubleshooting_de": [
            "ESP-Geraet auf Erreichbarkeit pruefen",
            "Schritt-Timeout-Konfiguration anpassen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5616: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Maximale Sequenz-Ausfuehrungsdauer ueberschritten",
        "message_user_de": "Sequenz hat die maximale Laufzeit ueberschritten",
        "troubleshooting_de": [
            "Sequenz-Schritte auf Dauer pruefen",
            "Maximale Dauer in der Konfiguration erhoehen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5617: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Kein Executor fuer Aktionstyp gefunden",
        "message_user_de": "Sequenz: Kein Handler fuer diesen Aktionstyp",
        "troubleshooting_de": [
            "Aktionstyp pruefen",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5618: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Zirkulaere Sequenzreferenz erkannt",
        "message_user_de": "Sequenz enthaelt eine Endlosschleife (zirkulaere Referenz)",
        "troubleshooting_de": [
            "Sequenz-Schritte auf zirkulaere Abhaengigkeiten pruefen",
            "Sequenz-Referenzen aufloesen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5630: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Sequenz-Task Erstellung fehlgeschlagen",
        "message_user_de": "Sequenz konnte nicht gestartet werden",
        "troubleshooting_de": [
            "Server-Logs pruefen",
            "Systemressourcen pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5631: {
        "category": "SEQUENCE",
        "severity": "error",
        "message_de": "Interner Sequenzfehler",
        "message_user_de": "Interner Fehler waehrend der Sequenzausfuehrung",
        "troubleshooting_de": [
            "Server-Logs auf Details pruefen",
            "Sequenz erneut starten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5632: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz-Bereinigung fehlgeschlagen",
        "message_user_de": "Abgeschlossene Sequenz konnte nicht bereinigt werden",
        "troubleshooting_de": [
            "Server-Logs pruefen",
            "Sequenz-Status manuell pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
    5633: {
        "category": "SEQUENCE",
        "severity": "critical",
        "message_de": "Sequenz-Zustand korrumpiert",
        "message_user_de": "Sequenzstatus ist inkonsistent",
        "troubleshooting_de": [
            "Server-Logs pruefen",
            "Alle aktiven Sequenzen stoppen und neu starten",
            "Server neustarten falls Problem fortbesteht",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5640: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Aktor durch andere Sequenz gesperrt",
        "message_user_de": "Aktor ist durch eine aktive Sequenz oder Regel gesperrt",
        "troubleshooting_de": [
            "Aktive Sequenzen pruefen: GET /api/v1/sequences/running",
            "Laufende Sequenz abwarten oder stoppen",
            "Force-Release nur im Notfall verwenden",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5641: {
        "category": "SEQUENCE",
        "severity": "warning",
        "message_de": "Sequenz Rate-Limit ueberschritten",
        "message_user_de": "Sequenz: Rate-Limit erreicht",
        "troubleshooting_de": [
            "Ausloesehaeufigkeit der Sequenz pruefen",
            "Wartezeit zwischen Ausfuehrungen erhoehen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5642: {
        "category": "SAFETY",
        "severity": "warning",
        "message_de": "Aktion durch Sicherheitssystem blockiert",
        "message_user_de": "Diese Aktion wurde vom Sicherheitssystem verhindert.",
        "troubleshooting_de": [
            "Sicherheitsregeln pruefen",
            "Aktuelle Sensor-Werte pruefen",
            "Sicherheitssystem ist korrekt aktiv — Grenzen pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # Logic Engine Errors (5700-5749)
    # =========================================================================
    5700: {
        "category": "LOGIC",
        "severity": "error",
        "message_de": "Logik-Regel nicht gefunden",
        "message_user_de": "Die angeforderte Automatisierungsregel existiert nicht.",
        "troubleshooting_de": [
            "Regel-ID in der Logic-View pruefen",
            "Regel wurde moeglicherweise geloescht",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5701: {
        "category": "LOGIC",
        "severity": "warning",
        "message_de": "Logik-Regel Validierung fehlgeschlagen",
        "message_user_de": "Die Regel-Konfiguration ist ungueltig.",
        "troubleshooting_de": [
            "Regel-Bedingungen pruefen",
            "Sensoren und Aktoren muessen konfiguriert sein",
            "Schwellenwerte muessen im gueltigen Bereich liegen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5702: {
        "category": "LOGIC",
        "severity": "error",
        "message_de": "Logik-Regel Ausfuehrung fehlgeschlagen",
        "message_user_de": "Logikregel: Ausfuehrung fehlgeschlagen",
        "troubleshooting_de": [
            "Regel-Konfiguration pruefen",
            "Aktor-Status pruefen",
            "Server-Logs auf Details pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5703: {
        "category": "LOGIC",
        "severity": "critical",
        "message_de": "Rueckkopplungsschleife in Logik-Regeln erkannt",
        "message_user_de": "Logikregel: Endlosschleife erkannt",
        "troubleshooting_de": [
            "Regeln auf zirkulaere Abhaengigkeiten pruefen",
            "Konflikt zwischen Regeln aufloesen",
            "Betroffene Regeln deaktivieren bis Problem geloest ist",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5704: {
        "category": "LOGIC",
        "severity": "error",
        "message_de": "Logik-Regel Bedingung ungueltig",
        "message_user_de": "Logikregel: Bedingung ungueltig konfiguriert",
        "troubleshooting_de": [
            "Bedingungsfelder auf Korrektheit pruefen",
            "Sensor-ID und Schwellenwerte pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5705: {
        "category": "LOGIC",
        "severity": "error",
        "message_de": "Logik-Regel Aktion fehlgeschlagen",
        "message_user_de": "Logikregel: Aktion fehlgeschlagen",
        "troubleshooting_de": [
            "Aktor-Konfiguration pruefen",
            "ESP-Geraet auf Erreichbarkeit pruefen",
            "Sicherheitsregeln pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # Dashboard Errors (5750-5779)
    # =========================================================================
    5750: {
        "category": "DASHBOARD",
        "severity": "error",
        "message_de": "Dashboard nicht gefunden",
        "message_user_de": "Das angeforderte Dashboard existiert nicht.",
        "troubleshooting_de": [
            "Dashboard-ID pruefen",
            "Dashboard wurde moeglicherweise geloescht",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # Subzone Errors (5780-5799)
    # =========================================================================
    5780: {
        "category": "SUBZONE",
        "severity": "error",
        "message_de": "Subzone nicht gefunden",
        "message_user_de": "Die angeforderte Subzone existiert nicht.",
        "troubleshooting_de": [
            "Subzone-ID pruefen",
            "Subzone muss zuerst auf dem ESP konfiguriert werden",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    # =========================================================================
    # AutoOps Errors (5800-5849)
    # =========================================================================
    5800: {
        "category": "AUTOOPS",
        "severity": "error",
        "message_de": "AutoOps-Job fehlgeschlagen",
        "message_user_de": "Der automatische Konfigurationsjob ist fehlgeschlagen.",
        "troubleshooting_de": [
            "Job-Details in den AutoOps-Reports pruefen",
            "Alle Services muessen laufen (Server, MQTT, DB)",
            "Job erneut starten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    # =========================================================================
    # Notification Errors (5850-5899) — Phase 4A
    # =========================================================================
    5850: {
        "category": "NOTIFICATION",
        "severity": "error",
        "message_de": "Benachrichtigung nicht gefunden",
        "message_user_de": "Die angeforderte Benachrichtigung existiert nicht.",
        "troubleshooting_de": [
            "Benachrichtigungs-ID pruefen",
            "Benachrichtigung wurde moeglicherweise geloescht oder bereinigt",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5851: {
        "category": "NOTIFICATION",
        "severity": "error",
        "message_de": "Benachrichtigung konnte nicht gesendet werden",
        "message_user_de": "Die Benachrichtigung konnte nicht zugestellt werden.",
        "troubleshooting_de": [
            "Email-Service-Konfiguration pruefen (EMAIL_ENABLED)",
            "Provider-Zugangsdaten pruefen",
            "Server-Logs auf detaillierte Fehlermeldung pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5852: {
        "category": "NOTIFICATION",
        "severity": "critical",
        "message_de": "Email-Provider nicht verfuegbar",
        "message_user_de": "Der Email-Service ist nicht konfiguriert oder nicht erreichbar.",
        "troubleshooting_de": [
            "EMAIL_ENABLED Umgebungsvariable pruefen",
            "SMTP/Resend Provider-Konfiguration pruefen",
            "Netzwerkverbindung zum Email-Provider pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5853: {
        "category": "NOTIFICATION",
        "severity": "error",
        "message_de": "Email-Template fehlt oder ungueltig",
        "message_user_de": "Keine Email-Adresse oder Template fuer den Versand verfuegbar.",
        "troubleshooting_de": [
            "Email-Adresse in den Benachrichtigungseinstellungen hinterlegen",
            "Oder Email-Adresse direkt in der Anfrage angeben",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5854: {
        "category": "NOTIFICATION",
        "severity": "warning",
        "message_de": "Digest-Zeitplan ungueltig",
        "message_user_de": "Der konfigurierte Zusammenfassungs-Zeitplan ist ungueltig.",
        "troubleshooting_de": [
            "Zeitplan-Konfiguration in den Einstellungen pruefen",
            "Gueltige Werte: daily, weekly, none",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5855: {
        "category": "NOTIFICATION",
        "severity": "warning",
        "message_de": "Alert-Unterdrueckungskonfiguration ungueltig",
        "message_user_de": "Die Konfiguration fuer die Benachrichtigungsunterdrueckung ist fehlerhaft.",
        "troubleshooting_de": [
            "Unterdrueckungsregeln pruefen",
            "Zeitfenster muessen gueltig sein (Start vor Ende)",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5856: {
        "category": "NOTIFICATION",
        "severity": "warning",
        "message_de": "Unterdrueckungsfenster-Konflikt",
        "message_user_de": "Das neue Zeitfenster ueberlappt mit einem bestehenden.",
        "troubleshooting_de": [
            "Bestehende Unterdrueckungsfenster pruefen",
            "Ueberlappende Zeitraeume anpassen oder zusammenfuehren",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5857: {
        "category": "NOTIFICATION",
        "severity": "warning",
        "message_de": "Webhook-Payload ungueltig",
        "message_user_de": "Der empfangene Webhook-Payload hat ein ungueltiges Format.",
        "troubleshooting_de": [
            "Grafana Alert-Konfiguration pruefen",
            "Webhook-URL und Format ueberpruefen",
            "Payload muss dem Alertmanager-Format entsprechen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5858: {
        "category": "NOTIFICATION",
        "severity": "error",
        "message_de": "Webhook-Signatur ungueltig",
        "message_user_de": "Die Signatur des Webhooks konnte nicht verifiziert werden.",
        "troubleshooting_de": [
            "Webhook-Secret in Grafana und Server abgleichen",
            "Signatur-Header pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5859: {
        "category": "NOTIFICATION",
        "severity": "error",
        "message_de": "Alert-Praeferenz nicht gefunden",
        "message_user_de": "Fuer dieses Geraet existieren keine Alert-Einstellungen.",
        "troubleshooting_de": [
            "Alert-Einstellungen im Geraetedetail konfigurieren",
            "Standard-Einstellungen werden automatisch erstellt",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    # =========================================================================
    # Plugin Errors (5900-5949)
    # =========================================================================
    5900: {
        "category": "PLUGIN",
        "severity": "error",
        "message_de": "Plugin nicht in Registry gefunden",
        "message_user_de": "Plugin nicht gefunden",
        "troubleshooting_de": [
            "Plugin-ID in der Plugin-Verwaltung pruefen",
            "Plugin wurde moeglicherweise deinstalliert",
            "Plugin-Registry auf Vollstaendigkeit pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5901: {
        "category": "PLUGIN",
        "severity": "warning",
        "message_de": "Plugin ist deaktiviert",
        "message_user_de": "Plugin deaktiviert",
        "troubleshooting_de": [
            "Plugin in der Verwaltungsoberflaeche aktivieren",
            "Berechtigungen pruefen",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5902: {
        "category": "PLUGIN",
        "severity": "error",
        "message_de": "Plugin-Ausfuehrung fehlgeschlagen",
        "message_user_de": "Plugin-Ausfuehrung fehlgeschlagen",
        "troubleshooting_de": [
            "Plugin-Konfiguration pruefen",
            "Server-Logs auf Details pruefen",
            "Plugin neu starten oder deaktivieren",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5903: {
        "category": "PLUGIN",
        "severity": "error",
        "message_de": "Plugin-Konfiguration ungueltig",
        "message_user_de": "Plugin: Ungueltige Konfiguration",
        "troubleshooting_de": [
            "Plugin-Konfiguration in der Verwaltung pruefen",
            "Pflichtfelder ausfuellen",
            "Konfigurationsformat pruefen",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5904: {
        "category": "PLUGIN",
        "severity": "error",
        "message_de": "Plugin-Rollback fehlgeschlagen",
        "message_user_de": "Plugin: Rollback fehlgeschlagen",
        "troubleshooting_de": [
            "Plugin-Status manuell pruefen",
            "Server-Logs auf Details pruefen",
            "Plugin manuell deaktivieren und neu konfigurieren",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5905: {
        "category": "PLUGIN",
        "severity": "warning",
        "message_de": "Plugin-Authentifizierung fehlgeschlagen",
        "message_user_de": "Plugin: Authentifizierung fehlgeschlagen",
        "troubleshooting_de": [
            "Plugin-Zugangsdaten pruefen",
            "API-Key oder Token erneuern",
            "Plugin-Konfiguration aktualisieren",
        ],
        "docs_link": None,
        "recoverable": False,
        "user_action_required": True,
    },
    5906: {
        "category": "PLUGIN",
        "severity": "warning",
        "message_de": "Plugin-Zeitplan ungueltig",
        "message_user_de": "Plugin: Zeitplan ungueltig konfiguriert",
        "troubleshooting_de": [
            "Cron-Ausdruck oder Schedule-Konfiguration pruefen",
            "Gueltiges Zeitplan-Format verwenden",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": True,
    },
    5907: {
        "category": "PLUGIN",
        "severity": "error",
        "message_de": "Plugin-Registry Synchronisation fehlgeschlagen",
        "message_user_de": "Plugin: Registry-Synchronisation fehlgeschlagen",
        "troubleshooting_de": [
            "Server-Logs auf Details pruefen",
            "Plugin-Registry auf Konsistenz pruefen",
            "Server neustarten",
        ],
        "docs_link": None,
        "recoverable": True,
        "user_action_required": False,
    },
}


def get_server_error_info(code: int) -> Optional[Dict[str, Any]]:
    """Returns enrichment data for a server error code, or None if not found."""
    return SERVER_ERROR_MAPPING.get(code)


def get_all_server_error_codes() -> Dict[int, Dict[str, Any]]:
    """Returns the complete server error mapping dict."""
    return SERVER_ERROR_MAPPING
